import { useEffect, useState } from 'react';
import { Link, useParams, Navigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  AlertTriangle,
  ArrowLeft,
  Check,
  ExternalLink,
  Shield,
  Star,
  X,
} from 'lucide-react';
import type { CryptoCard } from '../types/card';
import { fetchCardById, fetchCardArticle } from '../lib/supabase';
import SmartCardImage from '../components/SmartCardImage';
import CryptoIcon from '../components/CryptoIcon';
import TrustBadge from '../components/TrustBadge';
import { useAppStore } from '../store/useAppStore';
import { useLocalizedRoute } from '../hooks/useLocalizedRoute';
import { useLanguage } from '../hooks/useLanguage';
import { useSeoMeta } from '../hooks/useSeoMeta';
import Breadcrumb from '../components/Breadcrumb';
import { fmtEUR, fmtPct } from '../utils/format';
import { getExtraLabel } from '../i18n/extrasLabels';
import {
  CARD_COMPARISONS, CARD_NAMES, CARD_REVIEW_SLUGS,
  COMPARE_SEG, REVIEW_SEG, THEMATIC_SLUGS, THEMATIC_LABELS,
  comparisonSlug,
} from '../data/internalLinks';

const CARD_SEGMENT: Record<string, string> = {
  fr: 'cartes', de: 'karten', es: 'tarjetas', it: 'carte', en: 'cards',
};
const HOME_LABEL: Record<string, string> = {
  fr: 'Accueil', de: 'Startseite', es: 'Inicio', it: 'Home', en: 'Home',
};

/**
 * Maps bad "card IDs" that were generated by AI in article links (e.g. /cartes/cashback)
 * to the correct thematic page slug for each language.
 */
const THEMATIC_SLUGS: Record<string, Record<string, string>> = {
  cashback:     { fr: 'carte-crypto-cashback',        de: 'krypto-karte-cashback',        es: 'tarjeta-cripto-cashback',          it: 'carta-cripto-cashback',        en: 'crypto-card-cashback' },
  comparatif:   { fr: 'meilleure-carte-crypto',        de: 'beste-krypto-karte',            es: 'mejor-tarjeta-cripto',             it: 'migliore-carta-cripto',        en: 'best-crypto-card' },
  meilleure:    { fr: 'meilleure-carte-crypto',        de: 'beste-krypto-karte',            es: 'mejor-tarjeta-cripto',             it: 'migliore-carta-cripto',        en: 'best-crypto-card' },
  best:         { fr: 'meilleure-carte-crypto',        de: 'beste-krypto-karte',            es: 'mejor-tarjeta-cripto',             it: 'migliore-carta-cripto',        en: 'best-crypto-card' },
  'sans-frais': { fr: 'carte-crypto-sans-frais',       de: 'krypto-karte-ohne-jahresgebuehr', es: 'tarjeta-cripto-sin-comisiones',  it: 'carta-cripto-senza-commissioni', en: 'crypto-card-no-fees' },
  'no-fees':    { fr: 'carte-crypto-sans-frais',       de: 'krypto-karte-ohne-jahresgebuehr', es: 'tarjeta-cripto-sin-comisiones',  it: 'carta-cripto-senza-commissioni', en: 'crypto-card-no-fees' },
  'sans-staking': { fr: 'carte-crypto-sans-staking',   de: 'krypto-karte-ohne-staking',      es: 'tarjeta-cripto-sin-staking',      it: 'carta-cripto-senza-staking',   en: 'crypto-card-no-staking' },
  'no-staking': { fr: 'carte-crypto-sans-staking',    de: 'krypto-karte-ohne-staking',      es: 'tarjeta-cripto-sin-staking',      it: 'carta-cripto-senza-staking',   en: 'crypto-card-no-staking' },
  virtuelle:    { fr: 'carte-crypto-virtuelle',        de: 'virtuelle-krypto-karte',         es: 'tarjeta-crypto-virtual',          it: 'carta-crypto-virtuale',        en: 'virtual-crypto-card' },
  virtual:      { fr: 'carte-crypto-virtuelle',        de: 'virtuelle-krypto-karte',         es: 'tarjeta-crypto-virtual',          it: 'carta-crypto-virtuale',        en: 'virtual-crypto-card' },
  debutant:     { fr: 'cartes-crypto-debutant',        de: 'krypto-karten-einsteiger',       es: 'tarjetas-crypto-principiante',    it: 'carte-crypto-principiante',    en: 'beginner-crypto-cards' },
  beginner:     { fr: 'cartes-crypto-debutant',        de: 'krypto-karten-einsteiger',       es: 'tarjetas-crypto-principiante',    it: 'carte-crypto-principiante',    en: 'beginner-crypto-cards' },
  france:       { fr: 'cartes-crypto-france',          de: 'krypto-karten-deutschland',      es: 'tarjetas-crypto-espana',          it: 'carte-crypto-italia',          en: 'crypto-cards-europe' },
};

/** Formats an unknown extras key as readable text: self_custody → Self custody */
function formatExtra(key: string): string {
  return key.replace(/_/g, ' ').replace(/^\w/, c => c.toUpperCase());
}

export default function CardDetail() {
  const { id } = useParams<{ id: string }>();
  const { t } = useTranslation(['cards', 'common']);
  const { getRoute } = useLocalizedRoute();
  const lang = useLanguage();
  const favorites = useAppStore((s) => s.favorites);
  const toggleFavorite = useAppStore((s) => s.toggleFavorite);

  const [card, setCard] = useState<CryptoCard | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [article, setArticle] = useState<any>(null);

  useEffect(() => {
    if (!id) return;
    setLoading(true);
    setNotFound(false);
    fetchCardById(id)
      .then((c) => {
        if (!c) setNotFound(true);
        else setCard(c);
      })
      .finally(() => setLoading(false));
  }, [id]);

  useEffect(() => {
    if (id && lang) fetchCardArticle(id, lang).then(setArticle);
  }, [id, lang]);

  // ── SEO: centralized via useSeoMeta ──────────────────────────────────────────
  const year = new Date().getFullYear();
  const seoTitle = card
    ? (article?.meta_title || `${card.name} ${year} : ${card.cashbackPremium > 0 ? `jusqu'à ${card.cashbackPremium}% cashback — ` : ''}Avis et test complet | TopCryptoCards`)
    : 'TopCryptoCards';
  const seoDesc = card
    ? (article?.meta_description || `Avis complet ${year} sur la ${card.name} par ${card.issuer}. Cashback ${card.cashbackPremium}%${card.annualFees === 0 ? ', sans frais annuels' : `, frais ${card.annualFees} €/an`}${card.stakingRequired ? `, staking requis` : ''}. Notre verdict.`)
    : '';
  useSeoMeta({ title: seoTitle, description: seoDesc, image: card?.realCardImage || undefined, type: 'article' });

  // ── Schema.org FinancialProduct + AggregateRating ────────────────────────────
  useEffect(() => {
    if (!card) return;

    const schema: Record<string, unknown> = {
      '@context': 'https://schema.org',
      '@type': 'FinancialProduct',
      name: card.name,
      description: article?.excerpt || seoDesc,
      url: `https://topcryptocards.eu/${lang}/${CARD_SEGMENT[lang] || 'cards'}/${card.id}`,
      image: card.realCardImage || '',
      provider: { '@type': 'Organization', name: card.issuer },
      feesAndCommissionsSpecification: card.annualFees > 0 ? `${card.annualFees} €/an` : 'Gratuit',
      offers: {
        '@type': 'Offer',
        price: String(card.annualFees || 0),
        priceCurrency: 'EUR',
        availability: 'https://schema.org/InStock',
      },
      additionalProperty: [
        { '@type': 'PropertyValue', name: 'Cashback', value: `${card.cashbackPremium || card.cashbackBase || 0}%` },
        { '@type': 'PropertyValue', name: 'Réseau', value: card.cardNetwork || 'Visa/Mastercard' },
      ],
    };

    // AggregateRating — from trustScore (0–100 → 0–10)
    if (card.trustScore != null && card.trustScore > 0) {
      schema.aggregateRating = {
        '@type': 'AggregateRating',
        ratingValue: Math.round(card.trustScore / 10 * 10) / 10,
        bestRating: 10,
        worstRating: 1,
        ratingCount: 1,
      };
    }

    document.getElementById('schema-financial-product')?.remove();
    const schemaEl = document.createElement('script');
    schemaEl.id = 'schema-financial-product';
    schemaEl.type = 'application/ld+json';
    schemaEl.textContent = JSON.stringify(schema);
    document.head.appendChild(schemaEl);

    return () => {
      document.getElementById('schema-financial-product')?.remove();
    };
  }, [card, article, lang, seoDesc]);

  // ── Schema.org FAQPage ────────────────────────────────────────────────────────
  useEffect(() => {
    if (!card) return;

    const name = card.name;
    const cashback = card.cashbackPremium || card.cashbackBase || 0;
    const fees = card.annualFees;
    const network = card.cardNetwork || 'Visa/Mastercard';
    const staking = card.stakingRequired;

    type FaqItem = { q: string; a: string };
    const faqsByLang: Record<string, FaqItem[]> = {
      fr: [
        {
          q: `La ${name} est-elle gratuite ?`,
          a: fees === 0 ? `Oui, la ${name} ne nécessite aucun frais annuel.` : `La ${name} coûte ${fees} €/an.`,
        },
        {
          q: `Quel est le cashback de la ${name} ?`,
          a: cashback > 0
            ? `La ${name} offre jusqu'à ${cashback}% de cashback en cryptomonnaies.`
            : `La ${name} n'offre pas de cashback standard.`,
        },
        {
          q: `La ${name} nécessite-t-elle du staking ?`,
          a: staking
            ? `Oui, la ${name} nécessite un staking minimum pour bénéficier de tous les avantages.`
            : `Non, la ${name} ne nécessite aucun staking.`,
        },
        {
          q: `Sur quel réseau fonctionne la ${name} ?`,
          a: `La ${name} fonctionne sur le réseau ${network}.`,
        },
      ],
      de: [
        {
          q: `Ist die ${name} kostenlos ?`,
          a: fees === 0 ? `Ja, die ${name} hat keine Jahresgebühren.` : `Die ${name} kostet ${fees} €/Jahr.`,
        },
        {
          q: `Welches Cashback bietet die ${name} ?`,
          a: cashback > 0
            ? `Die ${name} bietet bis zu ${cashback}% Cashback in Kryptowährungen.`
            : `Die ${name} bietet kein Standard-Cashback.`,
        },
        {
          q: `Erfordert die ${name} Staking ?`,
          a: staking
            ? `Ja, die ${name} erfordert ein Mindest-Staking für die vollen Vorteile.`
            : `Nein, die ${name} erfordert kein Staking.`,
        },
        {
          q: `In welchem Netzwerk funktioniert die ${name} ?`,
          a: `Die ${name} läuft im ${network}-Netzwerk.`,
        },
      ],
      es: [
        {
          q: `¿Es gratuita la ${name} ?`,
          a: fees === 0 ? `Sí, la ${name} no tiene tarifas anuales.` : `La ${name} cuesta ${fees} €/año.`,
        },
        {
          q: `¿Qué cashback ofrece la ${name} ?`,
          a: cashback > 0
            ? `La ${name} ofrece hasta un ${cashback}% de cashback en criptomonedas.`
            : `La ${name} no ofrece cashback estándar.`,
        },
        {
          q: `¿La ${name} requiere staking ?`,
          a: staking
            ? `Sí, la ${name} requiere un staking mínimo para acceder a todos los beneficios.`
            : `No, la ${name} no requiere staking.`,
        },
        {
          q: `¿En qué red funciona la ${name} ?`,
          a: `La ${name} funciona en la red ${network}.`,
        },
      ],
      it: [
        {
          q: `La ${name} è gratuita ?`,
          a: fees === 0 ? `Sì, la ${name} non ha costi annuali.` : `La ${name} costa ${fees} €/anno.`,
        },
        {
          q: `Quale cashback offre la ${name} ?`,
          a: cashback > 0
            ? `La ${name} offre fino al ${cashback}% di cashback in criptovalute.`
            : `La ${name} non offre cashback standard.`,
        },
        {
          q: `La ${name} richiede staking ?`,
          a: staking
            ? `Sì, la ${name} richiede uno staking minimo per ottenere tutti i vantaggi.`
            : `No, la ${name} non richiede staking.`,
        },
        {
          q: `Su quale rete funziona la ${name} ?`,
          a: `La ${name} funziona sulla rete ${network}.`,
        },
      ],
      en: [
        {
          q: `Is the ${name} free ?`,
          a: fees === 0 ? `Yes, the ${name} has no annual fees.` : `The ${name} costs €${fees}/year.`,
        },
        {
          q: `What cashback does the ${name} offer ?`,
          a: cashback > 0
            ? `The ${name} offers up to ${cashback}% cashback in cryptocurrencies.`
            : `The ${name} does not offer standard cashback.`,
        },
        {
          q: `Does the ${name} require staking ?`,
          a: staking
            ? `Yes, the ${name} requires a minimum staking to unlock the full benefits.`
            : `No, the ${name} does not require any staking.`,
        },
        {
          q: `What network does the ${name} use ?`,
          a: `The ${name} runs on the ${network} network.`,
        },
      ],
    };

    const faqs = faqsByLang[lang] ?? faqsByLang.en;
    const faqSchema = {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faqs.map(({ q, a }) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    };

    document.getElementById('schema-faq-card')?.remove();
    const faqEl = document.createElement('script');
    faqEl.id = 'schema-faq-card';
    faqEl.type = 'application/ld+json';
    faqEl.textContent = JSON.stringify(faqSchema);
    document.head.appendChild(faqEl);

    return () => { document.getElementById('schema-faq-card')?.remove(); };
  }, [card, lang]);

  if (loading) {
    return (
      <div className="container-app py-12 max-w-4xl">
        <div className="animate-pulse space-y-6">
          <div className="h-6 bg-bg-elevated rounded w-32" />
          <div className="flex gap-6">
            <div className="h-48 w-72 bg-bg-elevated rounded-2xl shrink-0" />
            <div className="flex-1 space-y-3">
              <div className="h-8 bg-bg-elevated rounded w-1/2" />
              <div className="h-5 bg-bg-elevated rounded w-1/3" />
              <div className="h-24 bg-bg-elevated rounded" />
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (notFound || !card) {
    // If the ID is a known thematic keyword (e.g. /cartes/cashback from AI-generated links),
    // silently redirect to the correct thematic page instead of showing "not found".
    if (id && THEMATIC_SLUGS[id]) {
      const slug = THEMATIC_SLUGS[id][lang] || THEMATIC_SLUGS[id].en;
      return <Navigate to={`/${lang}/${slug}`} replace />;
    }
    return (
      <div className="container-app py-24 text-center">
        <Shield className="w-14 h-14 text-slate-600 mx-auto mb-4" />
        <h1 className="text-3xl font-display font-bold text-white mb-2">
          {t('common:card_not_found_title')}
        </h1>
        <p className="text-slate-500 mb-8">{t('common:card_not_found_desc')}</p>
        <Link to={getRoute('compare')} className="btn-primary">
          <ArrowLeft className="w-4 h-4" />
          {t('common:btn_back')}
        </Link>
      </div>
    );
  }

  const isFav = favorites.includes(card.id);
  const restrictionEntries = Object.entries(card.marketRestrictions);

  // Split article content into 3 parts:
  // 1. Pure article body (before thematic links)
  // 2. Thematic + comparison injected links
  // 3. FAQ (rendered last)
  const content = article?.content || '';
  const thematicSep = '<div class="see-also-thematic"';
  const faqSep = '<div data-faq="v1"';
  const thematicIdx = content.indexOf(thematicSep);
  const faqIdx = content.indexOf(faqSep);
  const articleBodyHtml = thematicIdx > 0 ? content.slice(0, thematicIdx) : content;
  const injectedLinksHtml = thematicIdx > 0
    ? (faqIdx > 0 ? content.slice(thematicIdx, faqIdx) : content.slice(thematicIdx))
    : '';
  const articleFaqHtml = faqIdx > 0 ? content.slice(faqIdx) : '';

  return (
    <div className="animate-fade-in">
      {/* Breadcrumb */}
      <div className="container-app pt-6 pb-2">
        <Breadcrumb items={[
          { label: HOME_LABEL[lang] || 'Home', href: `/${lang}` },
          { label: t('common:card_detail_back'), href: getRoute('compare') },
          { label: card.name },
        ]} />
      </div>

      {/* Hero */}
      <div
        className="relative overflow-hidden"
        style={{
          background: `linear-gradient(135deg, ${card.colorPrimary}18 0%, ${card.colorSecondary}10 100%)`,
        }}
      >
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-bg/80 pointer-events-none" />
        <div className="container-app py-10 relative">
          <div className="flex flex-col md:flex-row gap-8 items-start md:items-center">
            <SmartCardImage card={card} size="lg" className="shrink-0 w-full max-w-[280px] mx-auto md:mx-0" priority />
            <div className="flex-1 min-w-0">
              {card.badge && (
                <span
                  className="inline-block px-3 py-1 rounded-full text-xs font-bold mb-3 border"
                  style={{
                    color: card.colorPrimary,
                    borderColor: `${card.colorPrimary}40`,
                    background: `${card.colorPrimary}12`,
                  }}
                >
                  {card.badge}
                </span>
              )}
              <h1 className="text-4xl font-display font-bold text-white mb-1">
                {card.name}
              </h1>
              <p className="text-slate-400 text-lg mb-4">{card.issuer}</p>

              {card.virtualOnly && (
                <div className="mb-4 inline-flex items-center gap-2 px-3 py-2 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400 text-sm">
                  <AlertTriangle className="w-4 h-4 shrink-0" />
                  {t('cards:virtual_only_warning')}
                </div>
              )}

              {restrictionEntries.length > 0 && (
                <div className="mb-4 space-y-1">
                  {restrictionEntries.map(([market, reason]) => (
                    <div
                      key={market}
                      className="inline-flex items-start gap-2 px-3 py-2 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-xs mr-2"
                    >
                      <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                      <span>
                        <span className="font-semibold uppercase">{market}</span> — {reason}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              <div className="flex flex-wrap gap-3">
                <button
                  onClick={() => toggleFavorite(card.id)}
                  className={`btn-secondary ${isFav ? 'border-green-accent/50 text-green-accent' : ''}`}
                >
                  <Star className="w-4 h-4" fill={isFav ? 'currentColor' : 'none'} />
                  {t('common:nav_favorites')}
                </button>
                <a
                  href={card.affiliateLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-primary"
                >
                  {t('common:quiz_see_offer')}
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container-app py-10">
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main column */}
          <div className="lg:col-span-2 space-y-8">

            {/* Key stats */}
            <section>
              <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                {t('cards:card_extras')}
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                <StatCard label={t('cards:cashback_base')} value={fmtPct(card.cashbackBase)} />
                <StatCard
                  label={t('cards:cashback_premium')}
                  value={fmtPct(card.cashbackPremium)}
                  highlight
                  color={card.colorPrimary}
                />
                <StatCard
                  label={t('cards:card_fees')}
                  value={card.annualFees === 0 ? t('common:home_card_free') : fmtEUR(card.annualFees)}
                />
                <StatCard
                  label={t('cards:card_staking')}
                  value={card.stakingRequired === 0 ? t('common:compare_stat_none') : fmtEUR(card.stakingRequired)}
                />
                <StatCard label={t('cards:card_daily_limit')} value={fmtEUR(card.dailyLimit)} />
                <StatCard label={t('cards:card_network')} value={card.cardNetwork} />
              </div>
            </section>

            {/* Article body (pure content, no links, no FAQ) */}
            <style>{`
              .card-article h2 { font-size: 1.5rem; font-weight: 700; color: #ffffff; margin: 2rem 0 0.75rem; }
              .card-article h3 { font-size: 1.2rem; font-weight: 600; color: #e2e8f0; margin: 1.5rem 0 0.5rem; }
              .card-article p  { margin-bottom: 1rem; line-height: 1.7; }
              .card-article ul, .card-article ol { margin: 0.75rem 0 1rem 1.5rem; }
              .card-article li { margin-bottom: 0.4rem; }
            `}</style>
            {articleBodyHtml && (
              <div
                className="card-surface card-article p-6"
                dangerouslySetInnerHTML={{ __html: articleBodyHtml }}
              />
            )}

            {/* Availability */}
            <section>
              <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                {t('common:card_detail_availability')}
              </h2>
              <div className="grid grid-cols-2 gap-2">
                <Pill ok={card.availableFrance} label={t('cards:card_available_france')} />
                <Pill ok={card.availableEU} label={t('cards:card_available_eu')} />
                <Pill ok={card.freeWithdrawals} label={t('cards:card_free_withdrawals')} />
                <Pill ok={card.stakingRequired === 0} label={t('common:filter_no_staking')} />
              </div>
            </section>

            {/* Extras */}
            {card.extras.filter((e) => e !== 'virtual_only').length > 0 && (
              <section>
                <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                  {t('cards:card_extras')}
                </h2>
                <ul className="space-y-2">
                  {card.extras
                    .filter((e) => e !== 'virtual_only')
                    .map((e) => (
                      <li key={e} className="flex items-start gap-2 text-slate-300">
                        <Check className="w-4 h-4 text-green-accent shrink-0 mt-0.5" />
                        <span>{getExtraLabel(e, lang)}</span>
                      </li>
                    ))}
                </ul>
              </section>
            )}

            {/* Supported cryptos */}
            {card.cryptos.length > 0 && (
              <section>
                <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                  {t('cards:card_cryptos')}
                </h2>
                <div className="flex flex-wrap gap-2">
                  {card.cryptos.map((c) => (
                    <div
                      key={c}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-bg-elevated border border-bg-border"
                    >
                      <CryptoIcon symbol={c} size={16} />
                      <span className="text-sm text-slate-300 font-medium">{c}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* Thematic + comparison links — after card detail sections */}
            {injectedLinksHtml && (
              <div
                className="card-surface card-article p-6"
                dangerouslySetInnerHTML={{ __html: injectedLinksHtml }}
              />
            )}

            {/* FAQ — very last, just above footer */}
            {articleFaqHtml && (
              <div
                className="card-surface card-article p-6"
                dangerouslySetInnerHTML={{ __html: articleFaqHtml }}
              />
            )}

            {/* ── Comparaisons disponibles pour cette carte ── */}
            {CARD_COMPARISONS[card.id] && CARD_COMPARISONS[card.id].length > 0 && (
              <section className="card-surface p-6">
                <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                  {lang === 'de' ? `${card.name} vergleichen` :
                   lang === 'es' ? `Comparar ${card.name}` :
                   lang === 'it' ? `Confronta ${card.name}` :
                   lang === 'en' ? `Compare ${card.name}` :
                   `Comparer ${card.name}`}
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {CARD_COMPARISONS[card.id].slice(0, 6).map(partnerId => (
                    <Link
                      key={partnerId}
                      to={`/${lang}/${COMPARE_SEG[lang] || 'comparer'}/${comparisonSlug(card.id, partnerId)}`}
                      className="flex items-center justify-between gap-2 p-3 rounded-xl bg-bg-elevated border border-bg-border hover:border-cyan-accent/40 hover:text-cyan-accent transition-colors group text-sm"
                    >
                      <span className="text-slate-300 group-hover:text-cyan-accent transition-colors">
                        {card.name} <span className="text-slate-500">vs</span> {CARD_NAMES[partnerId] || partnerId}
                      </span>
                      <ArrowLeft className="w-3.5 h-3.5 rotate-180 shrink-0 text-slate-600 group-hover:text-cyan-accent transition-colors" />
                    </Link>
                  ))}
                </div>
              </section>
            )}

            {/* ── Guides thématiques liés ── */}
            {(() => {
              const themes: string[] = ['best'];
              if (card.cashbackPremium > 0) themes.push('cashback');
              if (card.annualFees === 0) themes.push('no-fees');
              if (card.stakingRequired === 0) themes.push('no-staking');
              if (CARD_REVIEW_SLUGS[card.id]) themes.push('__review__');
              return (
                <section className="card-surface p-6">
                  <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4">
                    {lang === 'de' ? 'Thematische Guides' :
                     lang === 'es' ? 'Guías temáticas' :
                     lang === 'it' ? 'Guide tematiche' :
                     lang === 'en' ? 'Thematic guides' :
                     'Guides thématiques'}
                  </h2>
                  <ul className="space-y-2">
                    {themes.filter(t => t !== '__review__').map(theme => (
                      <li key={theme}>
                        <Link
                          to={`/${lang}/${THEMATIC_SLUGS[theme]?.[lang] || THEMATIC_SLUGS[theme]?.fr || ''}`}
                          className="flex items-center gap-2 text-sm text-slate-300 hover:text-cyan-accent transition-colors group"
                        >
                          <ArrowLeft className="w-3 h-3 rotate-180 text-slate-600 group-hover:text-cyan-accent shrink-0" />
                          {THEMATIC_LABELS[theme]?.[lang] || THEMATIC_LABELS[theme]?.fr}
                        </Link>
                      </li>
                    ))}
                    {CARD_REVIEW_SLUGS[card.id] && (
                      <li>
                        <Link
                          to={`/${lang}/${REVIEW_SEG[lang] || 'avis'}/${CARD_REVIEW_SLUGS[card.id]}`}
                          className="flex items-center gap-2 text-sm text-slate-300 hover:text-cyan-accent transition-colors group"
                        >
                          <ArrowLeft className="w-3 h-3 rotate-180 text-slate-600 group-hover:text-cyan-accent shrink-0" />
                          {lang === 'de' ? `${card.name} Testbericht` :
                           lang === 'es' ? `Opinión sobre ${card.name}` :
                           lang === 'it' ? `Recensione ${card.name}` :
                           lang === 'en' ? `${card.name} review` :
                           `Avis ${card.name}`}
                        </Link>
                      </li>
                    )}
                  </ul>
                </section>
              );
            })()}

          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Trust score — hidden */}
            {false && card.trustScore !== undefined && (
              <div className="p-5 rounded-2xl bg-bg-elevated border border-bg-border">
                <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-400 mb-4 flex items-center gap-1.5">
                  <Shield className="w-3.5 h-3.5" />
                  {t('common:trust_score')}
                </h3>
                <TrustBadge card={card} variant="detail" />
              </div>
            )}

            {/* CTA */}
            <div className="p-5 rounded-2xl border border-bg-border bg-bg-elevated">
              <p className="text-sm text-slate-400 mb-4 leading-relaxed">
                {t('common:card_detail_cta_desc')}
              </p>
              <a
                href={card.affiliateLink}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary w-full"
              >
                {t('common:quiz_see_offer')}
                <ExternalLink className="w-4 h-4" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({
  label,
  value,
  highlight,
  color,
}: {
  label: string;
  value: string;
  highlight?: boolean;
  color?: string;
}) {
  return (
    <div className="p-4 rounded-xl bg-bg-elevated border border-bg-border">
      <div className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">{label}</div>
      <div
        className={`text-lg font-semibold ${highlight ? '' : 'text-white'}`}
        style={highlight && color ? { color } : undefined}
      >
        {value}
      </div>
    </div>
  );
}

function Pill({ ok, label }: { ok: boolean; label: string }) {
  return (
    <div
      className={`px-3 py-2 rounded-lg flex items-center gap-2 border text-sm ${
        ok
          ? 'bg-green-accent/5 border-green-accent/30 text-green-accent'
          : 'bg-bg-elevated border-bg-border text-slate-500'
      }`}
    >
      {ok ? <Check className="w-3.5 h-3.5 shrink-0" /> : <X className="w-3.5 h-3.5 shrink-0" />}
      {label}
    </div>
  );
}