/*
  # Insert all missing crypto cards (~80 cartes)

  Cartes déjà en DB (à ne PAS réinsérer) :
    binance-standard, bit2me-card, bitpanda-card, bybit-card, coinbase-card,
    crypto-com-frosted-rose, crypto-com-jade-green, crypto-com-midnight-blue,
    crypto-com-royal-indigo, crypto-com-ruby-steel, nexo-card, plutus-card,
    revolut-metal, trade-republic-card, wirex-elite, wirex-standard,
    young-platform-card, kraken-krak-card, okx-card

  Sources : opencryptocards.com, cccompare.xyz, research juin 2026
*/

INSERT INTO cards (
  id, name, issuer,
  cashback_base, cashback_premium,
  annual_fees, staking_required,
  cryptos,
  available_france, available_eu,
  card_network,
  daily_limit, free_withdrawals,
  extras,
  affiliate_link,
  badge,
  color_primary, color_secondary,
  real_card_image, image_alt,
  markets,
  status, virtual_only, market_restrictions
) VALUES

-- ─────────────────────────────────────────────
-- CARTES MAJEURES EUROPE (connues du grand public)
-- ─────────────────────────────────────────────

('ready-card',
 'Ready Card', 'Ready',
 0.5, 3.0,
 0, 0,
 ARRAY['BTC','ETH','STRK','USDC','USDT'],
 true, true,
 'Mastercard',
 5000, true,
 ARRAY['self_custody','no_fx_fees','cashback_in_strk','apple_pay','google_pay'],
 'https://www.ready.co/card',
 NULL,
 '#6366F1', '#1E1B4B',
 NULL, 'Ready Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('metamask-card',
 'MetaMask Card', 'Consensys',
 1.0, 3.0,
 199, 0,
 ARRAY['ETH','USDC','USDT','WBTC','DAI','MATIC','BNB','AVAX'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['self_custody','no_fx_fees','web3_native','apple_pay','google_pay'],
 'https://metamask.io/card/',
 NULL,
 '#F6851B', '#161616',
 NULL, 'MetaMask Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('kast-card',
 'KAST Card', 'KAST Tech',
 2.0, 8.0,
 0, 0,
 ARRAY['USDC','USDT','BTC','ETH','MOVE'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['cashback_in_move_tokens','150_countries','no_fees'],
 'https://www.kast.xyz/',
 NULL,
 '#7C3AED', '#2E1065',
 NULL, 'KAST Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('deblock-card',
 'Deblock Card', 'Deblock',
 0.1, 1.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL','XRP'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['french_iban','mica_compliant','self_custody','sepa_free','no_fx_fees'],
 'https://deblock.com/en-FR',
 'MiCA FR',
 '#0EA5E9', '#0C4A6E',
 NULL, 'Deblock Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('whitebit-nova',
 'WhiteBIT Nóva', 'Wallester AS',
 1.0, 10.0,
 0, 0,
 ARRAY['BTC','ETH','WBT','USDT','USDC','SOL','XRP','ADA'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['cashback_up_to_10','no_fees','no_fx_fees','apple_pay'],
 'https://whitebit.com/crypto-card',
 NULL,
 '#F7941D', '#1A1A2E',
 NULL, 'WhiteBIT Nóva Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('gnosis-pay-card',
 'Gnosis Pay Card', 'Monavate Ltd',
 1.0, 5.0,
 0, 0,
 ARRAY['USDC','EURe','GBPe','GNO','WETH'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','on_chain_payments','no_fees','no_fx_fees','gnosis_chain'],
 'https://gnosispay.com/card',
 NULL,
 '#04795B', '#002018',
 NULL, 'Gnosis Pay Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('ether-fi-cash',
 'Ether.fi Cash', 'Ether.Fi Cash Ltd',
 2.0, 3.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','WBTC','weETH'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['self_custody','defi_native','no_fees','cashback_in_eth','web3'],
 'https://www.ether.fi/cash',
 NULL,
 '#627EEA', '#1A1A2E',
 NULL, 'Ether.fi Cash Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('1inch-card',
 '1inch Card', 'Monavate Ltd',
 1.0, 2.0,
 0, 0,
 ARRAY['USDC','1INCH','ETH','USDT'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['hybrid_custody','no_fees','defi_native'],
 'https://1inch.com/card',
 NULL,
 '#D82122', '#1A1A2E',
 NULL, '1inch Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('uphold-card',
 'Uphold Card', 'Uphold',
 1.0, 6.0,
 0, 0,
 ARRAY['BTC','ETH','XRP','USDC','USDT','DOT','SOL','ADA','DOGE','LTC'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['no_fees','no_fx_fees','multi_asset','cashback_in_crypto'],
 'https://uphold.com/debit-card',
 NULL,
 '#0074E8', '#003070',
 NULL, 'Uphold Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('kucard',
 'KuCard', 'KuCoin',
 1.0, 3.0,
 0, 0,
 ARRAY['BTC','ETH','KCS','USDT','USDC','SOL','XRP'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['no_fees','cashback_in_kcs','kucoin_integration'],
 'https://www.kucoin.com/kucard',
 NULL,
 '#23AF91', '#0B0E11',
 NULL, 'KuCard by KuCoin',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('cex-io-card',
 'CEX.IO Card', 'Quicko Sp. z o.o.',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','XRP','USDT','USDC','LTC','BCH','XLM'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['no_fees','no_fx_fees','cexio_integration','instant_conversion'],
 'https://cex.io/getmydebitcard',
 NULL,
 '#2B73D2', '#0A1628',
 NULL, 'CEX.IO Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('holyheld-card',
 'Holyheld', 'Unlimit EU Ltd',
 0.5, 1.0,
 0, 0,
 ARRAY['USDC','USDT','ETH','DAI','MATIC'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['hybrid_custody','no_fees','defi_native','sepa'],
 'https://holyheld.com/',
 NULL,
 '#FF6B6B', '#1A1A2E',
 NULL, 'Holyheld Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('bleap-crypto-card',
 'Bleap Crypto Card', 'Unlimit EU Ltd',
 2.0, 2.0,
 0, 0,
 ARRAY['USDC','ETH','BTC','USDT'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','stablecoin_focus'],
 'https://www.bleap.finance/card/crypto-card',
 NULL,
 '#00C2FF', '#0A0E1A',
 NULL, 'Bleap Crypto Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('solflare-card',
 'Solflare Card', 'Solflare',
 0.0, 0.0,
 0, 0,
 ARRAY['SOL','USDC','BONK','JTO','WIF','PYTH'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['self_custody','solana_native','no_fees','web3'],
 'https://solflare.com/card',
 NULL,
 '#9945FF', '#19161C',
 NULL, 'Solflare Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('bitget-card',
 'Bitget Card', 'Bitget',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','BGB','USDT','USDC','SOL','XRP','ADA'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['no_fees','bitget_integration','instant_conversion'],
 'https://www.bitget.com/cards/landing',
 NULL,
 '#00B4D8', '#0A0E1A',
 NULL, 'Bitget Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('xportal-card',
 'xPortal Card', 'xPortal',
 0.1, 0.5,
 0, 0,
 ARRAY['EGLD','USDC','ETH','BTC','MEX'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','multiversx_native'],
 'https://xportal.com/card',
 NULL,
 '#23F7DD', '#000000',
 NULL, 'xPortal Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('redotpay-card',
 'RedotPay Card', 'RedotPay',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','BNB','XRP','SOL'],
 false, true,
 'Visa',
 5000, false,
 ARRAY['virtual_and_physical','no_fees','stablecoin_focus','100_countries'],
 'https://www.redotpay.com/',
 NULL,
 '#FF4D4D', '#1A1A2E',
 NULL, 'RedotPay Crypto Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('tap-card',
 'Tap Card', 'Tap Global Ltd',
 0.5, 8.0,
 0, 0,
 ARRAY['BTC','ETH','XTP','USDC','USDT','XRP','LTC','BCH'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['no_fees','cashback_in_xtp','multi_tier'],
 'https://withtap.com/',
 NULL,
 '#00D4AA', '#0A1628',
 NULL, 'Tap Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('brighty-card',
 'Brighty Card', 'Wireflexion sp. z o.o.',
 0.5, 1.75,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','eu_iban','sepa'],
 'https://brighty.app/',
 NULL,
 '#7B5EA7', '#1A1232',
 NULL, 'Brighty Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('rebind-card',
 'Rebind Card', 'Rebind SAS',
 1.0, 5.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL','MATIC'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','french_company'],
 'https://rebind.co/',
 NULL,
 '#6C47FF', '#1A1A2E',
 NULL, 'Rebind Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

-- ─────────────────────────────────────────────
-- CARTES DeFi / SELF-CUSTODY
-- ─────────────────────────────────────────────

('cardano-card',
 'Cardano Card', 'Wirex',
 1.0, 8.0,
 0, 0,
 ARRAY['ADA','BTC','ETH','WXT','USDC','USDT'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['no_fees','no_fx_fees','cardano_native','cashback_in_ada'],
 'https://cardanocard.io/',
 NULL,
 '#0033AD', '#001A5E',
 NULL, 'Cardano Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('coca-visa-card',
 'COCA Visa Card', 'COCA',
 1.0, 8.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','COC'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','high_cashback','web3'],
 'https://www.coca.xyz/',
 NULL,
 '#FF6B35', '#1A0A00',
 NULL, 'COCA Visa Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('cypher-card',
 'Cypher Card', 'CypherD Wallet Inc',
 0.0, 0.35,
 0, 0,
 ARRAY['ETH','USDC','USDT','MATIC','BNB','SOL'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','multi_chain','web3'],
 'https://cypherhq.io/',
 NULL,
 '#00E5FF', '#0A0E1A',
 NULL, 'Cypher Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('offramp-spend-card',
 'Offramp Spend Card', 'Offramp Labs',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','DAI','WBTC'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','defi_native'],
 'https://app.offramp.xyz/',
 NULL,
 '#10B981', '#064E3B',
 NULL, 'Offramp Spend Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('spritz-card',
 'Spritz Card', 'Spritz Finance',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','DAI','USDT','WBTC','MATIC'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','no_fees','no_fx_fees','bill_pay'],
 'https://www.spritz.finance/spritz-card',
 NULL,
 '#9B5DE5', '#3A0068',
 NULL, 'Spritz Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('solid-card',
 'Solid Card', 'Solid',
 2.0, 5.0,
 0, 0,
 ARRAY['SOL','USDC','USDT','ETH','BTC'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','solana_native','cashback'],
 'https://www.solid.xyz/card',
 NULL,
 '#9945FF', '#19161C',
 NULL, 'Solid Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),


('thorwallet-card',
 'THORWallet Card', 'EMM Ventures AG',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','RUNE','USDC','USDT'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','thorchain_native'],
 'https://www.thorwallet.org/cards',
 NULL,
 '#33FF99', '#0A1628',
 NULL, 'THORWallet Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('zebec-card',
 'Zebec Card', 'Zebec Network',
 0.0, 0.0,
 0, 0,
 ARRAY['SOL','USDC','ZBC','BTC','ETH'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['self_custody','no_fx_fees','streaming_payments'],
 'https://zebec.io/cards',
 NULL,
 '#7B2FBE', '#1A0A2E',
 NULL, 'Zebec Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('ur-debit-card',
 'UR Debit Card', 'UR',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','BTC','SOL'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['hybrid_custody','no_fees','web3'],
 'https://get.ur.app/',
 NULL,
 '#FF3B30', '#1A0000',
 NULL, 'UR Debit Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('fuse-card',
 'Fuse Card', 'Lead Bank',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','FUSE','ETH'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','fuse_network'],
 'https://fusewallet.com/',
 NULL,
 '#B5E4CA', '#0A2E1A',
 NULL, 'Fuse Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('moonwell-card',
 'Moonwell Card', 'CypherD Wallet Inc.',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','ETH','WELL','cbBTC'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['hybrid_custody','no_fees','defi_lending','base_chain'],
 'https://card.moonwell.fi',
 NULL,
 '#7B2FBE', '#1A0A2E',
 NULL, 'Moonwell Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('swype-fun-card',
 'Swype.fun Card', 'BrahmaFi Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','ETH','USDT'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','no_fees','defi_native'],
 'https://swype.fun/',
 NULL,
 '#FF6B6B', '#1A0A0A',
 NULL, 'Swype.fun Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('exodus-spend-card',
 'Exodus Spend Card', 'Exodus Movement',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','SOL','XRP','USDC','USDT','ADA','DOGE'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','multi_chain','exodus_wallet'],
 'https://www.exodus.com/card',
 NULL,
 '#0B0C22', '#8B5CF6',
 NULL, 'Exodus Spend Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

-- ─────────────────────────────────────────────
-- CARTES STABLECOIN / PREPAID
-- ─────────────────────────────────────────────

('tuyo-card',
 'Tuyo Card', 'Tuyo Inc.',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','USDT'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','no_fees','stablecoin_focus','eea_latam'],
 'https://tuyo.com/',
 NULL,
 '#00C2A8', '#003330',
 NULL, 'Tuyo Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('fiat24-debit',
 'Fiat24 Debit', 'SR Saphirstein AG',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['no_fees','swiss_iban','blockchain_bank','sepa'],
 'https://www.fiat24.com/',
 NULL,
 '#2B2D42', '#EDF2F4',
 NULL, 'Fiat24 Debit Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('bitrefill-card',
 'Bitrefill Card', 'Airfill Prepaid AB',
 1.0, 2.0,
 0, 0,
 ARRAY['BTC','ETH','LTC','DOGE','USDT','USDC'],
 true, true,
 'Visa',
 2000, false,
 ARRAY['no_fees','no_fx_fees','gift_cards','lightning_network'],
 'https://www.bitrefill.com/card/',
 NULL,
 '#FF9900', '#1A1A2E',
 NULL, 'Bitrefill Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('coin98-fusion-card',
 'Coin98 Fusion Card', 'Ninety Eight',
 0.5, 2.0,
 0, 0,
 ARRAY['C98','BTC','ETH','USDC','USDT','SOL','BNB'],
 true, true,
 'Mastercard',
 3000, false,
 ARRAY['hybrid_custody','no_fees','multi_chain','web3'],
 'https://coin98.com/fusion-card',
 NULL,
 '#D4A017', '#1A1208',
 NULL, 'Coin98 Fusion Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('rizon-visa-card',
 'Rizon Visa Card', 'Rizon',
 0.1, 5.0,
 0, 0,
 ARRAY['ATOLO','BTC','ETH','USDC','USDT'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','no_fees','cosmos_native'],
 'https://rizon.world/',
 NULL,
 '#6B7280', '#1F2937',
 NULL, 'Rizon Visa Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('avalanche-card',
 'Avalanche Card', 'Rain Liquidity',
 0.0, 0.0,
 0, 0,
 ARRAY['AVAX','USDC','USDT','BTC','ETH'],
 true, true,
 'Mastercard',
 5000, false,
 ARRAY['no_fees','avalanche_native','defi_spending'],
 'https://www.avalanchecard.com/',
 NULL,
 '#E84142', '#2D0000',
 NULL, 'Avalanche Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('ugly-visa-card',
 'Ugly Visa', 'UglyCash',
 1.0, 4.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['no_fees','cashback','fun_design'],
 'https://ugly.cash/',
 NULL,
 '#FF6B6B', '#1A0A0A',
 NULL, 'Ugly Visa Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

-- ─────────────────────────────────────────────
-- CARTES BANCAIRES CRYPTO / NEO-BANQUES
-- ─────────────────────────────────────────────

('blackcatcard',
 'Blackcatcard', 'Papaya Ltd.',
 0.5, 5.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','XRP'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['no_fees','eu_iban','multi_currency','sepa'],
 'https://blackcatcard.com/',
 NULL,
 '#1A1A1A', '#FF4757',
 NULL, 'Blackcatcard',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('banxe-card',
 'Banxe Card', 'Tompay LTD',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','XRP','BNB'],
 true, true,
 'Mastercard',
 10000, true,
 ARRAY['hybrid_custody','no_fees','eu_iban','crypto_exchange'],
 'https://banxe.com/personal/debit-card/',
 NULL,
 '#1E3A5F', '#00B4D8',
 NULL, 'Banxe Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('nebeus-card',
 'Nebeus Card', 'Rintral Trading',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','XRP','LTC'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['no_fees','no_fx_fees','crypto_backed_loans','eu_iban'],
 'https://nebeus.com/nebeus-card',
 NULL,
 '#0D47A1', '#001560',
 NULL, 'Nebeus Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('cryptolife-card',
 'CryptoLife Card', 'Baanx Group Ltd',
 1.0, 2.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','XRP','SOL'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['no_fees','no_fx_fees','multi_currency'],
 'https://www.withcl.com/card',
 NULL,
 '#1A1A2E', '#4A90E2',
 NULL, 'CryptoLife Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('tonhub-card',
 'Tonhub Card', 'Walleexer s.r.o.',
 0.0, 0.0,
 0, 0,
 ARRAY['TON','USDT','BTC','ETH'],
 true, true,
 'Mastercard',
 3000, false,
 ARRAY['hybrid_custody','no_fees','no_fx_fees','ton_native'],
 'https://tonhub.com/',
 NULL,
 '#0088CC', '#003366',
 NULL, 'Tonhub Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('trustee-plus-card',
 'Trustee Plus Card', 'Trustee Global UAB',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','LTC','XRP'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['no_fees','no_fx_fees','eu_iban','non_custodial'],
 'https://trusteeglobal.eu/',
 NULL,
 '#2196F3', '#0D47A1',
 NULL, 'Trustee Plus Crypto Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('coinzoom-card',
 'CoinZoom Card', 'Zenus Bank',
 0.5, 5.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','XRP','LTC','ZOOM'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['no_fees','no_fx_fees','cashback_in_zoom','sepa'],
 'https://www.coinzoom.com/cards/',
 NULL,
 '#1565C0', '#0D47A1',
 NULL, 'CoinZoom Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('trastra-crypto-card',
 'TRASTRA Crypto Card', 'TRASTRA Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','LTC','XRP','BCH'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['no_fees','eu_iban','sepa','instant_conversion'],
 'https://trastra.com/',
 NULL,
 '#1A237E', '#E8EAF6',
 NULL, 'TRASTRA Crypto Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('utorg-crypto-card',
 'Utorg Crypto Card', 'UTORG LABS',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','SOL','XRP'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','instant_offramp'],
 'https://utorg.com/crypto-card',
 NULL,
 '#6C63FF', '#1A1832',
 NULL, 'Utorg Crypto Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('pexx-card',
 'PEXX Card', 'PEXX Technology HK Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','SOL'],
 true, true,
 'Mastercard',
 5000, false,
 ARRAY['no_fees','stablecoin_focus','sepa'],
 'https://pexx.com/card',
 NULL,
 '#0052CC', '#002266',
 NULL, 'PEXX Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('quicko-digital-card',
 'Quicko Digital Card', 'Quicko sp. z o.o.',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','eu_iban','instant_conversion'],
 'https://qdcard.io/',
 NULL,
 '#FF6600', '#1A1A1A',
 NULL, 'Quicko Digital Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('bitnob-virtual-card',
 'Bitnob Virtual Card', 'Bitnob',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','USDT','USDC'],
 true, true,
 'Visa',
 2000, false,
 ARRAY['no_fees','no_fx_fees','virtual_only','bitcoin_focus'],
 'https://bitnob.com/',
 'Virtuelle uniquement',
 '#F7931A', '#1A0A00',
 NULL, 'Bitnob Virtual Card',
 ARRAY['fr','de','es','it'],
 'active', true, '{}'),

('xplace-card',
 'XPlace Card', 'Pontech Group L.L.C-FZ',
 0.5, 2.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','SOL','XRP'],
 true, true,
 'Mastercard',
 5000, false,
 ARRAY['self_custody','no_fees','multi_chain'],
 'https://x.place/',
 NULL,
 '#0033A0', '#001A50',
 NULL, 'XPlace Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

-- ─────────────────────────────────────────────
-- CARTES PLUS NICHÉES / ÉCOSYSTÈME SPÉCIFIQUE
-- ─────────────────────────────────────────────

('wallbit-card',
 'Wallbit Card', 'Wallbit LLC',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','freelancer_focus','eu_uk'],
 'https://www.wallbit.io/card',
 NULL,
 '#FF4500', '#1A0800',
 NULL, 'Wallbit Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('avici-card',
 'Avici Card', 'Avici Inc.',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','BTC'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','no_fx_fees'],
 'https://avici.io/',
 NULL,
 '#00BCD4', '#006064',
 NULL, 'Avici Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('stables-card',
 'Stables Card', 'Stables Group',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','USDT','DAI','EURC'],
 false, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','stablecoin_only','global'],
 'https://www.stables.money/spend',
 NULL,
 '#10B981', '#064E3B',
 NULL, 'Stables Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('laso-card',
 'Laso Card', 'Laso Finance',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 false, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','defi_native'],
 'https://laso.finance/',
 NULL,
 '#8B5CF6', '#4C1D95',
 NULL, 'Laso Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('pay3-card',
 'Pay3 Card', 'Pay3 Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','BTC','SOL'],
 true, true,
 'Visa',
 3000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','web3'],
 'https://pay-3.io/',
 NULL,
 '#FF6B35', '#1A0500',
 NULL, 'Pay3 Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('chainscard',
 'ChainsCard', 'AI MARKETING & TECH LIMITED',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','BNB'],
 false, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','no_fx_fees','global'],
 'https://chainscard.io/',
 NULL,
 '#1A1A2E', '#4A90E2',
 NULL, 'ChainsCard',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('cryptocash-card',
 'CryptoCash Card', 'CryptoCash',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 false, true,
 'Mastercard',
 3000, false,
 ARRAY['no_fees','no_fx_fees'],
 'https://thecryptocash.co/',
 NULL,
 '#F59E0B', '#78350F',
 NULL, 'CryptoCash Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('senturopay-card',
 'SentüroPay Card', 'Senturo Pay Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 true, true,
 'Mastercard',
 3000, false,
 ARRAY['no_fees','no_fx_fees','eu_iban'],
 'https://senturopay.com/',
 NULL,
 '#1565C0', '#0D47A1',
 NULL, 'SentüroPay Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('onboard-flex-card',
 'Onboard Flex Card', 'Onboard',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','BTC','SOL'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['hybrid_custody','no_fees','web3'],
 'https://www.onboard.xyz/cards',
 NULL,
 '#7C3AED', '#2E1065',
 NULL, 'Onboard Flex Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('based-card',
 'Based Card', 'Xfers Pte. Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','cbBTC'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['hybrid_custody','no_fees','base_chain_native'],
 'https://basedapp.io/',
 NULL,
 '#0052FF', '#001A80',
 NULL, 'Based Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('mpcvault-card',
 'MPCVault Card', 'Third National',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL'],
 false, true,
 'Visa',
 5000, false,
 ARRAY['self_custody','no_fees','mpc_security','institutional'],
 'https://mpcvault.com/card',
 NULL,
 '#1A1A2E', '#4A90E2',
 NULL, 'MPCVault Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('exa-card',
 'Exa Card', 'Exa Labs SAS',
 0.0, 0.0,
 0, 0,
 ARRAY['USDC','ETH','OP','ARB'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','no_fees','optimism_native','exactly_protocol'],
 'https://www.exactly.app/exa-card',
 NULL,
 '#00E5FF', '#001A1A',
 NULL, 'Exa Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('tevau-card',
 'Tevau Card', 'Tevau',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 false, true,
 'Mastercard',
 3000, false,
 ARRAY['no_fees','global'],
 'https://tevau.io/card',
 NULL,
 '#FF9800', '#E65100',
 NULL, 'Tevau Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('pintopay-card',
 'PintoPay Card', 'UANT Inc',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','TON'],
 true, true,
 'Visa',
 3000, false,
 ARRAY['no_fees','no_fx_fees','telegram_native'],
 'https://pintopay.com/',
 NULL,
 '#229ED9', '#0A3A5C',
 NULL, 'PintoPay Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('coinw-card',
 'CoinW Card', 'CoinW',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','CWT'],
 false, true,
 'Mastercard',
 5000, false,
 ARRAY['no_fees','no_fx_fees','coinw_integration'],
 'https://www.coinw.com/crypto-card',
 NULL,
 '#1A237E', '#3949AB',
 NULL, 'CoinW Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

-- ─────────────────────────────────────────────
-- CARTES AVEC CASHBACK ÉLEVÉ / RÉCOMPENSES
-- ─────────────────────────────────────────────

('mexc-ether-fi-card',
 'MEXC x ether.fi Card', 'Ether.fi',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','weETH','MEXC'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','defi_yield','mexc_integration'],
 'https://www.ether.fi/cash',
 NULL,
 '#627EEA', '#1A1A2E',
 NULL, 'MEXC x ether.fi Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('kardpay-card',
 'Kardpay Card', 'Kardpay FZCO',
 0.0, 8.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','SOL','XRP'],
 true, true,
 'Visa',
 10000, true,
 ARRAY['no_fees','no_fx_fees','high_cashback'],
 'https://www.kardpay.app/',
 NULL,
 '#FF3B5C', '#1A001A',
 NULL, 'Kardpay Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('solcard',
 'Solcard', 'SC PAYMENTS Ltd',
 0.0, 8.0,
 0, 0,
 ARRAY['SOL','USDC','BTC','ETH'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['no_fees','high_cashback','solana_ecosystem'],
 'https://www.solcard.cc/',
 NULL,
 '#9945FF', '#19161C',
 NULL, 'Solcard',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('kolo-card',
 'Kolo Card', 'Kolo',
 0.0, 5.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL'],
 true, true,
 'Mastercard',
 5000, true,
 ARRAY['no_fees','no_fx_fees','cashback'],
 'https://kolo.xyz/',
 NULL,
 '#FF6B6B', '#1A0A0A',
 NULL, 'Kolo Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

-- ─────────────────────────────────────────────
-- CARTES GLOBALES MAIS ACCESSIBLES EUROPE
-- ─────────────────────────────────────────────

('xapo-card',
 'Xapo Card', 'Xapo Bank Ltd',
 0.2, 1.1,
 1000, 0,
 ARRAY['BTC','USDC','USDT'],
 true, true,
 'Mastercard',
 50000, true,
 ARRAY['private_bank','no_fx_fees','bitcoin_savings','premium'],
 'https://www.xapobank.com/card',
 'Premium',
 '#1A1A2E', '#C9A84C',
 NULL, 'Xapo Bank Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('crydit-crypto-card',
 'Crydit Crypto Card', 'CRYDIT CAPITAL Ltd',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC','XRP','BNB'],
 true, true,
 'Mastercard',
 10000, false,
 ARRAY['no_fees','no_fx_fees','global_access'],
 'https://www.crydit.com/',
 NULL,
 '#00BCD4', '#006064',
 NULL, 'Crydit Crypto Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('kem-infinity-card',
 'Kem Infinity Card', 'Kemfinity s.r.o.',
 0.0, 3.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 true, true,
 'Mastercard',
 5000, false,
 ARRAY['global','no_fees','cashback'],
 'https://kemapp.io/cards',
 NULL,
 '#FF9900', '#1A0A00',
 NULL, 'Kem Infinity Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

('plasma-one-card',
 'Plasma One Card', 'Plasma Finance',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','USDT','MATIC','BNB','SOL'],
 true, true,
 'Visa',
 5000, true,
 ARRAY['self_custody','no_fees','no_fx_fees','defi_native','multi_chain'],
 'https://plasma.finance/',
 NULL,
 '#7B2FBE', '#1A0A2E',
 NULL, 'Plasma One Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}'),

-- Deblock already inserted above, skip

-- ─────────────────────────────────────────────
-- CARTES AVEC STAKING / REWARDS SPÉCIAUX
-- ─────────────────────────────────────────────

('tria-card',
 'Tria Card', 'Threely Dimensions Inc',
 1.5, 6.0,
 25, 0,
 ARRAY['ETH','USDC','BTC','SOL','MATIC'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['self_custody','cashback','multi_chain','account_abstraction'],
 'https://tria.so',
 NULL,
 '#FF6B6B', '#1A0A0A',
 NULL, 'Tria Card',
 ARRAY['fr','de','es','it'],
 'active', false, '{}'),

('orbitx-card',
 'OrbitX Card', 'OrbitX Network Group',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDT','USDC'],
 false, true,
 'Visa',
 3000, false,
 ARRAY['self_custody','web3_payments'],
 'https://orbitxpay.com/',
 NULL,
 '#1A1A2E', '#7B2FBE',
 NULL, 'OrbitX Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('amp-black-card',
 'AMP Black Card', 'Futarchy Alpha Inc.',
 0.0, 0.0,
 0, 0,
 ARRAY['ETH','USDC','AMP','USDT'],
 false, true,
 'Mastercard',
 5000, false,
 ARRAY['self_custody','no_fees','web3'],
 'https://www.getamppay.com/',
 NULL,
 '#000000', '#FFD700',
 NULL, 'AMP Black Card',
 ARRAY['de','es','it','en'],
 'active', false, '{"fr": "Disponibilité France à confirmer"}'),

('moonpay-card',
 'MoonPay Card', 'MoonPay',
 0.0, 0.0,
 0, 0,
 ARRAY['BTC','ETH','USDC','USDT','SOL','XRP'],
 true, true,
 'Visa',
 5000, false,
 ARRAY['no_fees','instant_purchase','global_coverage'],
 'https://www.moonpay.com/',
 NULL,
 '#7B2FBE', '#1A0A2E',
 NULL, 'MoonPay Card',
 ARRAY['fr','de','es','it','en'],
 'active', false, '{}');
