// ─────────────────────────────────────────────────────────────────────────────
// brandConfigPt.ts
// AUTO-GENERATED by scripts/generate-brand-translations.mjs
// DO NOT EDIT MANUALLY — re-run the script to regenerate.
// Placeholder until the generator is run: empty = brand pages fall back to EN.
// Merged into BRAND_CONFIG (seo.pt) by brandConfig.ts.
// ─────────────────────────────────────────────────────────────────────────────

export const BRAND_SEO_PT: Record<string, {
  title: string;
  description: string;
  intro: string;
  outro: string;
  rating?: number;
  pros?: string[];
  cons?: string[];
  faq?: Array<{ q: string; a: string }>;
}> = {};
