// ─────────────────────────────────────────────────────────────────────────────
// themeContentPt.ts
// AUTO-GENERATED by scripts/generate-theme-pt.mjs — DO NOT EDIT MANUALLY.
// Portuguese (pt-PT) overlay for THEME_SECTIONS + THEME_FAQ of ThematicPage.
// Placeholder until the generator runs (empty = pt falls back to EN sections).
// ─────────────────────────────────────────────────────────────────────────────

export const THEME_SECTIONS_PT: Record<string, { h2: string; p: string }[]> = {};

export const THEME_FAQ_PT: Record<string, { q: string; a: string }[]> = {};
