// ─────────────────────────────────────────────────────────────────────────────
// themeContentPt.ts — AUTO-GENERATED by scripts/generate-theme-pt.mjs
// DO NOT EDIT MANUALLY. Generated: 2026-09-07T12:04:39.176Z
// ─────────────────────────────────────────────────────────────────────────────

export const THEME_SECTIONS_PT: Record<string, { h2: string; p: string }[]> = {
  "2026": [
    {
      "h2": "Quais os cartões crypto indispensáveis em ${YEAR}?",
      "p": "Em 2026, o mercado dos cartões crypto consolidou-se em torno de alguns operadores sólidos: a Crypto.com mantém-se líder com o seu ecossistema completo, a Nexo destaca-se pelo cashback em BTC sem staking, e a Gnosis Pay ganha terreno com a sua proposta on-chain única. As recém-chegadas MetaMask Card e Ether.fi Card atraem utilizadores DeFi. A regulamentação MiCA na Europa traz maior transparência e segurança para os consumidores."
    },
    {
      "h2": "Tendências dos cartões crypto em 2026: MiCA, on-chain, stablecoins",
      "p": "A regulamentação MiCA (Markets in Crypto-Assets), plenamente em vigor desde 2025, obriga os emitentes a deter reservas e a publicar relatórios de conformidade. Como consequência, os cartões emitidos por operadores regulamentados na Europa (Crypto.com, Nexo, Revolut) estão agora mais protegidos. A tendência on-chain acelera-se com cartões como a Gnosis Pay, que liquida diretamente a partir da tua carteira, sem intermediários e com total transparência. Em Portugal, o Banco de Portugal supervisiona os prestadores de serviços de criptoativos no quadro do MiCA."
    },
    {
      "h2": "Como escolher o teu cartão crypto em ${YEAR} de acordo com o teu perfil?",
      "p": "Em 2026, a escolha de um cartão crypto depende sobretudo do teu uso principal. Viajas com frequência? A Crypto.com Jade ou Indigo oferecem acesso a lounges Priority Pass, seguro de viagem e cashback no Airbnb. Queres acumular Bitcoin? A Nexo Card oferece cashback em BTC sem staking obrigatório. És utilizador DeFi? A MetaMask Card ou a Gnosis Pay ligam diretamente à tua carteira. Estás a começar? A Brighty ou a Revolut Standard oferecem uma transição suave sem risco. A maturidade do mercado em 2026 significa que existe um cartão adaptado a cada perfil."
    },
    {
      "h2": "O que mudou em ${YEAR} para os cartões crypto na Europa",
      "p": "2026 marca uma viragem regulatória e tecnológica para os cartões crypto europeus. O MiCA é plenamente aplicável, afastando do mercado os emitentes não conformes. Os consumidores beneficiam de proteções semelhantes às da banca tradicional, incluindo em Portugal sob a supervisão do Banco de Portugal. A liquidação on-chain avança (Gnosis Pay, MetaMask Card, Ether.fi Card), os stablecoins impõem-se como meio de carregamento preferencial e as interfaces integram-se com as carteiras existentes. A barreira de entrada para o primeiro cartão crypto nunca foi tão baixa."
    },
    {
      "h2": "A nossa seleção dos melhores cartões crypto de ${YEAR} por categoria",
      "p": "Melhor cartão crypto para todos os perfis: Crypto.com Jade (cashback de 3%, lounges, seguros de viagem, reembolsos Airbnb/Expedia/Netflix). Melhor cartão sem staking: Gnosis Pay (2% on-chain, self-custody, rede xDAI). Melhor cartão para principiantes: Brighty (grátis, USDC, IBAN europeu, cashback de 1,75%). Melhor cartão para acumulação de BTC: Nexo Card (2% em BTC, sem staking). Melhor cartão DeFi-nativo: MetaMask Card (cashback em ETH, carteira direta). Em Portugal, importa recordar que os ganhos com criptoativos estão sujeitos a IRS à taxa autónoma de 28% se os ativos forem detidos há menos de 365 dias, sendo isentos após esse prazo; o pagamento com crypto constitui uma alienação tributável. Estas recomendações ${YEAR} baseiam-se na conformidade regulatória MiCA, na solidez financeira do emitente e no cashback efetivo após dedução dos custos de staking."
    }
  ],
  "best": [
    {
      "h2": "Como escolher o melhor cartão crypto em ${YEAR}?",
      "p": "Para identificar o melhor cartão crypto, analisa vários critérios: taxa máxima de cashback, condições de staking, comissões anuais, disponibilidade em Portugal e fiabilidade do emissor. Um cartão que oferece 8% de cashback com 200 000€ de staking em CRO não é rentável para um utilizador médio. Calcula o retorno real sobre o investimento tendo em conta o capital imobilizado e a volatilidade do token nativo."
    },
    {
      "h2": "Crypto.com, Nexo, Gnosis Pay: qual o cartão que te corresponde?",
      "p": "O Crypto.com destaca-se para os utilizadores já investidos em CRO, com um cashback de 1% a 8% consoante o nível. O Nexo atrai pelo seu cashback em BTC sem staking excessivo. O Gnosis Pay, cartão on-chain, oferece cashback em GNO sem KYC restrito. Para principiantes, o Brighty ou o MetaMask Card são ideais: grátis, sem staking obrigatório, com cashback de 0,5% a 3%."
    },
    {
      "h2": "Os 5 critérios que fazem realmente a diferença",
      "p": "Para além da taxa de cashback apresentada, cinco critérios separam os bons cartões dos maus em ${YEAR}. Em primeiro lugar, a crypto na qual é pago o cashback: um cashback em BTC (Nexo) é intrinsecamente mais estável do que um cashback em token proprietário volátil. Em segundo lugar, a disponibilidade efetiva em Portugal ou no país de residência. Em terceiro lugar, a qualidade do apoio ao cliente (prazos, idiomas, canais disponíveis). Em quarto lugar, a solidez financeira do emissor e a sua conformidade com o regulamento MiCA, supervisionado pelo Banco de Portugal. Em quinto lugar, os limites de levantamento em ATM e as comissões de câmbio no estrangeiro, critérios frequentemente negligenciados que podem custar caro no dia a dia."
    },
    {
      "h2": "Classificação por perfil: qual o cartão para cada utilizador?",
      "p": "Não existe um único \"melhor\" cartão — tudo depende da tua situação. Para o grande viajante: Crypto.com Jade ou Bybit, com acesso a lounges de aeroporto e 0% de comissões de câmbio. Para o investidor crypto DeFi: Gnosis Pay ou MetaMask Card, com cashback acumulado diretamente na tua wallet sem intermediários. Para o utilizador quotidiano sem staking: Brighty, Nexo ou MetaMask Card, grátis e sem condições. Para quem maximiza o cashback a todo o custo: Crypto.com Obsidian (8%), desde que aceite imobilizar 400 000 CRO. Compara o teu perfil com cada oferta antes de te comprometeres."
    },
    {
      "h2": "A nossa metodologia: como selecionamos e avaliamos os cartões crypto",
      "p": "Cada cartão crypto presente no TopCryptoCards foi avaliado segundo seis critérios ponderados: fiabilidade do emissor (30%), taxa de cashback real (20%), comissões totais (20%), disponibilidade geográfica (15%), experiência do utilizador (10%) e conformidade regulatória (5%). Note-se que, em Portugal, os ganhos resultantes de permutas de crypto detidas há menos de 365 dias estão sujeitos a uma taxa de 28%, sendo isentos após esse prazo; o pagamento com crypto constitui igualmente uma alienação tributável. Atualizamos esta classificação trimestralmente para refletir as alterações tarifárias, os novos operadores e as mudanças regulatórias, incluindo as decorrentes do regulamento MiCA. Apenas os cartões efetivamente disponíveis e testados pela nossa equipa são incluídos."
    }
  ],
  "cashback": [
    {
      "h2": "Como funciona o cashback num cartão crypto?",
      "p": "O cashback crypto funciona como um programa de fidelidade: cada compra devolve uma percentagem do valor gasto, paga em criptomoeda. Ao contrário do cashback bancário clássico pago em euros, o cashback crypto está sujeito à volatilidade do mercado. Um cashback de 3% em CRO num mês de queda pode valer menos do que um cashback de 1% em USDC estável. Escolhe a crypto de cashback em função da tua estratégia de investimento."
    },
    {
      "h2": "Staking e cashback: qual o retorno real sobre o investimento?",
      "p": "Para desbloquear as melhores taxas de cashback, alguns cartões exigem fazer staking de um montante elevado de tokens nativos. O cartão Crypto.com Obsidian oferece 8% de cashback, mas requer 400 000 CRO em staking (~150 000€). Com 1 000€ de despesas mensais, o cashback anual seria de 960€, insuficiente para rentabilizar a imobilização de 150 000€. Para a maioria dos utilizadores, os cartões com 1-3% de cashback sem staking são muito mais rentáveis a longo prazo."
    },
    {
      "h2": "Cashback em BTC, ETH ou token próprio: qual a diferença?",
      "p": "A escolha da crypto em que é pago o cashback tem um impacto direto no seu valor futuro. Um cashback em BTC ou ETH beneficia da valorização histórica desses ativos — se o Bitcoin subir 50% no ano, o teu cashback de 1% vale efetivamente 1,5% em euros. Já um cashback em CRO, BIT ou NEXO está sujeito ao desempenho do token próprio da plataforma, mais volátil. A Nexo permite escolher entre BTC e NEXO. A Gnosis Pay paga em GNO. A MetaMask Card paga em ETH. Identifica em que crypto pretendes constituir poupança antes de escolher."
    },
    {
      "h2": "Maximizar o cashback: as boas práticas",
      "p": "Para maximizar o teu cashback crypto, há várias estratégias a adotar. Concentra as despesas correntes num único cartão para atingir os eventuais limites mensais de cashback (alguns cartões limitam a 50 ou 100€/mês de cashback). Usa o teu cartão crypto para subscrições recorrentes — Netflix, Spotify, compras online —, compras que se acumulam mês após mês. Verifica se o teu cartão oferece cashback majorado em determinadas categorias, como restaurantes ou viagens. Por fim, mantém o teu cashback em vez de o vender imediatamente: deixa-o valorizar ao longo do tempo se estiveres otimista em relação à crypto associada."
    },
    {
      "h2": "Comparativo de cashback por cartão: resumo ${YEAR}",
      "p": "Melhores taxas de cashback em ${YEAR}: Crypto.com Obsidian 8% (400K CRO em staking), Crypto.com Jade 3% (50K CRO), Nexo Card 2% (em BTC ou NEXO, sem staking), Gnosis Pay 2% (em GNO, on-chain), Bitpanda 2% (em BEST), MetaMask Card 1-3% (em ETH, conforme volume), Brighty 1,75% (em USDC, sem staking), Revolut 1% (em crypto à escolha). Os cartões sem staking mais rentáveis para uso corrente continuam a ser a Nexo e a Gnosis Pay. Para volumes de despesa elevados, os cartões Crypto.com de 3-8% tornam-se competitivos apesar do staking exigido."
    },
    {
      "h2": "Fiscalidade do cashback crypto em Portugal: o que diz a lei",
      "p": "Em Portugal, o enquadramento fiscal das criptomoedas é regulado pelo Código do IRS e supervisionado pelo Banco de Portugal no âmbito do regulamento europeu MiCA. O cashback recebido em criptomoeda pode ser qualificado como rendimento no momento da receção, pelo que é aconselhável registar o valor em euros na data de cada pagamento. Na alienação posterior, a mais-valia é calculada sobre esse valor de aquisição. As mais-valias em criptoativos detidos por menos de 365 dias são tributadas a uma taxa autónoma de 28%; após um ano de detenção, ficam isentas de imposto. Atenção: pagar com crypto constitui uma alienação fiscalmente relevante, podendo gerar uma mais-valia tributável. Consulta um contabilista para a tua situação pessoal e mantém um registo rigoroso dos preços de aquisição do teu cashback."
    }
  ],
  "no-fees": [
    {
      "h2": "Por que escolher um cartão crypto sem comissões anuais?",
      "p": "As comissões anuais de um cartão crypto podem chegar aos 180€/ano nos níveis premium. Antes de pagar, calcula se as vantagens (cashback, lounges, subscrições) superam esse custo. Para um utilizador que gasta 500€/mês com um cashback de 1%, o ganho anual é de 60€, bem abaixo dos 180€ de comissões. Os cartões grátis como MetaMask Card, Gnosis Pay ou Brighty oferecem um excelente ponto de entrada sem compromisso financeiro."
    },
    {
      "h2": "Cartões crypto grátis: MetaMask, Gnosis Pay, Brighty, comparativo ${YEAR}",
      "p": "O MetaMask Card é totalmente grátis (0€/ano), disponível na rede Visa, com cashback de 1% em ETH nas compras do dia a dia, sem staking obrigatório. O Gnosis Pay, também grátis, é único enquanto cartão on-chain nativo, com cashback em GNO. O Brighty oferece um cartão USDC grátis com IBAN europeu integrado e até 1,75% de cashback. Estas três opções combinam as vantagens das fintech tradicionais com as da DeFi."
    },
    {
      "h2": "Comissões ocultas dos cartões crypto \"grátis\": o que é preciso verificar",
      "p": "Um cartão sem comissões anuais pode ainda assim gerar custos indiretos. Os mais comuns: comissões de câmbio nas compras em moeda estrangeira (geralmente entre 0 e 3%), comissões em ATM acima de um limite mensal grátis (200 a 400€ conforme o cartão), e por vezes comissões de inatividade se o cartão não for utilizado durante 12 meses. Antes de te inscreveres, lê a tabela de comissões completa no site oficial. O Gnosis Pay e o MetaMask Card distinguem-se pela total transparência nas suas condições tarifárias, sem surpresas."
    },
    {
      "h2": "Qual o cartão crypto grátis a escolher conforme o teu perfil de utilização?",
      "p": "A escolha depende do teu perfil. Se já és utilizador DeFi com uma wallet Ethereum, o MetaMask Card integra-se de forma natural, sem necessidade de qualquer conta centralizada. Se preferires um cartão associado a uma stablecoin (USDC) com IBAN europeu para receber o teu salário, o Brighty é a opção ideal. Se quiseres um cartão on-chain totalmente descentralizado com liquidação em xDAI, o Gnosis Pay é o mais avançado tecnicamente. Para os utilizadores que querem simplesmente um cashback simples sem comissões e sem complexidade cripto, o Revolut (nível Standard) continua a ser uma opção sólida na UE, combinando banco e cripto numa única app."
    },
    {
      "h2": "Cartões crypto sem comissões e staking: são realmente rentáveis?",
      "p": "Sim, e muitas vezes mais do que os cartões premium com staking. Tomemos o MetaMask Card como exemplo: 0€/ano de comissões, 1% de cashback em ETH em todas as compras. Com 1.000€ de despesas mensais, acumulas 120€ de cashback anual em ETH sem imobilizar capital. Compara com o Crypto.com Ruby Steel: 10€/mês, ou seja, 120€/ano de comissões, mais 2% de cashback (240€/ano em 1.000€/mês), com um ganho líquido de 120€, idêntico ao do MetaMask Card, mas com 350€ de CRO detidos. Quanto mais o CRO desvaloriza, menos favorável se torna este cálculo. Os cartões grátis sem staking eliminam esse risco por completo."
    }
  ],
  "no-staking": [
    {
      "h2": "Porquê preferir um cartão crypto sem staking?",
      "p": "O staking obrigatório apresenta dois riscos principais: imobilização de capital e exposição ao risco cambial sobre a crypto em staking. Se o preço colapsar durante o período de lock-up (muitas vezes 180 dias), perde-se duplamente — no valor em staking e nas oportunidades perdidas. Um cartão sem staking como o Gnosis Pay ou o MetaMask Card oferece cashback imediato sem restrições nem risco de perda adicional."
    },
    {
      "h2": "Gnosis Pay, MetaMask Card, Brighty: a comparação ${YEAR}",
      "p": "O Gnosis Pay é único: é o primeiro cartão Visa ligado diretamente a uma wallet on-chain, com cashback em GNO em cada compra. O MetaMask Card oferece 1 a 3% em ETH nas compras, ideal para utilizadores de DeFi. O Brighty propõe entre 0,5% e 1,75% de cashback em USDC sem staking, com um IBAN europeu integrado. Estes três cartões distinguem-se pela total transparência e pela ausência de condições ocultas."
    },
    {
      "h2": "Rendimento real: cartões sem staking vs. cartões com staking",
      "p": "A comparação numérica é frequentemente mais favorável aos cartões sem staking do que se pensa. Exemplo: o Gnosis Pay oferece 2% de cashback em GNO sem staking. O Crypto.com Ruby Steel oferece 2% em CRO, mas exige 350 CRO em staking (~210€ ao preço atual). Com 500€/mês de despesas, o Gnosis Pay gera 120€/ano em GNO, sem imobilização de capital. O Crypto.com gera os mesmos 120€ em CRO, mas com 210€ de capital bloqueado e exposto à volatilidade do CRO. Se o CRO descer 30%, o valor em staking diminui, tornando o cartão retrospetivamente menos rentável."
    },
    {
      "h2": "Cartões sem staking e DeFi: a convergência de ${YEAR}",
      "p": "Em ${YEAR}, os cartões crypto sem staking aproximam-se cada vez mais da DeFi: o Gnosis Pay liquida em xDAI on-chain, o MetaMask Card debita diretamente da wallet Ethereum do utilizador, e o Ether.fi Card está associado a ETH em staking líquido (faz-se staking mas mantém-se o controlo). Esta convergência permite acumular as vantagens da Web3 — self-custody, transparência, rendimento DeFi — com a comodidade de um cartão Visa aceite em todo o lado. Para um utilizador de DeFi, é a solução mais coerente com o seu ecossistema existente."
    },
    {
      "h2": "FAQ: todas as questões sobre cartões crypto sem staking",
      "p": "É possível obter mais de 2% de cashback sem staking? Em ${YEAR}, 2% continua a ser o limite máximo dos cartões sem staking (Gnosis Pay, Nexo). Um cartão sem staking é menos vantajoso? Não — a ausência de staking é, por si só, uma vantagem: o capital mantém-se líquido e acessível a qualquer momento. O Gnosis Pay é verdadeiramente on-chain? Sim, cada transação é liquidada diretamente na Gnosis Chain, sendo publicamente visível no explorador de blocos. Em Portugal, o cashback em crypto está sujeito a imposto? O uso de crypto como meio de pagamento constitui uma alienação tributável; as mais-valias são tributadas a 28% se o ativo for detido há menos de 365 dias, estando isentas após esse prazo, de acordo com as regras fiscais portuguesas supervisionadas pelo Banco de Portugal no quadro do MiCA. É possível perder o capital com um cartão sem staking? Não — o risco de perda limita-se à volatilidade do cashback recebido (em GNO, ETH ou USDC)."
    }
  ],
  "france": [
    {
      "h2": "Quais os cartões crypto realmente disponíveis em Portugal?",
      "p": "Nem todos os cartões crypto estão disponíveis em Portugal. Alguns, como o Coinbase Card, funcionam na UE mas com restrições. Os cartões disponíveis em Portugal e mais fiáveis são: Crypto.com Visa, Nexo Card, Bybit Card, Binance Card, OKX Card, Gnosis Pay, MetaMask Card, Brighty, Deblock e Revolut. Verifica sempre a disponibilidade no site oficial, pois as regras de conformidade podem mudar. Desde a entrada em vigor do MiCA (2025), os emitentes regulados na UE são obrigados a indicar claramente a sua cobertura geográfica."
    },
    {
      "h2": "Regulamentação MiCA e cartões crypto em Portugal: o que precisas de saber",
      "p": "O regulamento MiCA (Markets in Crypto-Assets), em vigor desde dezembro de 2024, impõe normas rigorosas aos emitentes de cartões crypto que operam em Portugal e na UE: reservas comprováveis, relatórios de transparência e proteção dos fundos dos clientes. O resultado prático é que emitentes regulados como Crypto.com, Nexo ou Revolut oferecem agora uma proteção comparável à da banca tradicional. Para os residentes em Portugal, isso traduz-se em maior segurança e em vias de recurso claras em caso de litígio. Dá sempre preferência a um cartão emitido por um operador com registo junto do Banco de Portugal ou com licença equivalente ao abrigo do MiCA."
    },
    {
      "h2": "Fiscalidade dos cartões crypto em Portugal em ${YEAR}",
      "p": "Em Portugal, cada utilização de um cartão crypto implica uma conversão de cripto para euros no momento do pagamento. Esta conversão constitui um facto tributável: as mais-valias realizadas estão sujeitas a uma taxa de 28% se o ativo tiver sido detido há menos de 365 dias; ao fim de um ano de detenção, as mais-valias ficam isentas de imposto. Pagar com crypto é sempre considerado uma alienação tributável, independentemente do prazo. Para simplificar a declaração, utiliza ferramentas como Waltio, Koinly ou CoinTracking para agregar automaticamente as transações. A estratégia mais simples para evitar eventos fiscais: carrega o cartão com stablecoins (USDC, USDT) — valor estável, sem mais-valia realizada, sem obrigação de declaração na conversão."
    },
    {
      "h2": "Melhores cartões crypto para residentes em Portugal em ${YEAR}",
      "p": "Para os residentes em Portugal, os cartões com melhor relação qualidade-preço são: Crypto.com Visa (ecossistema completo, 5 níveis, disponível em Portugal), Nexo Card (cashback em BTC sem staking), Gnosis Pay (on-chain, self-custody), MetaMask Card (nativa em DeFi, cashback em ETH), Brighty (grátis, USDC, IBAN europeu disponível) e Deblock (fintech crypto-friendly, IBAN europeu, interface intuitiva). Todos estes cartões dispõem de autorização regulatória válida em Portugal."
    },
    {
      "h2": "Abrir um cartão crypto a partir de Portugal: guia passo a passo em ${YEAR}",
      "p": "(1) Escolhe o teu cartão no TopCryptoCards de acordo com o teu perfil (cashback, staking, DeFi). (2) Cria uma conta na plataforma oficial — demora entre 5 a 10 minutos. (3) Completa o KYC: documento de identificação (cartão de cidadão ou passaporte) + selfie, validação em 24 a 72 horas. (4) Se o cartão o exigir, faz o staking do montante mínimo necessário (ex.: 350 CRO para o Crypto.com Ruby Steel). (5) Carrega via transferência SEPA a partir do teu banco português (Millennium BCP, Caixa Geral de Depósitos, Novo Banco, BPI…). (6) O cartão virtual fica disponível de imediato; o cartão físico chega em 5 a 10 dias úteis."
    }
  ],
  "virtual": [
    {
      "h2": "O que é um cartão crypto virtual e para que serve?",
      "p": "Um cartão crypto virtual funciona como um cartão físico, mas existe apenas em formato digital. Adicionas-o ao Apple Pay, Google Pay ou Samsung Pay para pagar online e em loja via NFC. A principal vantagem: ativação imediata (muitas vezes em menos de 5 minutos), sem demoras de entrega e possibilidade de gerar números únicos para proteger as tuas compras online contra fraude."
    },
    {
      "h2": "Melhores cartões crypto virtuais em ${YEAR}: Crypto.com, Wirex, Brighty",
      "p": "A Crypto.com disponibiliza um cartão virtual Visa ativável imediatamente, recarregável em crypto ou em euros. A Wirex oferece cartões virtuais multi-divisa com cashback em WXT. A Brighty fornece um cartão virtual USDC com IBAN europeu integrado. Para compras exclusivamente online, estes cartões virtuais são ideais: sem custos de envio, cashback desde a primeira compra e proteção total do número do cartão físico."
    },
    {
      "h2": "Cartão crypto virtual e segurança: o que é preciso saber",
      "p": "A segurança é um dos argumentos mais sólidos a favor dos cartões virtuais. Ao contrário de um cartão físico, o número virtual pode ser bloqueado ou regenerado com um clique na app caso se suspeite de fraude. Alguns emissores disponibilizam números de cartão de utilização única para compras em sites desconhecidos. Em caso de perda ou roubo do telemóvel, o cartão virtual fica protegido pelo código PIN da app e pela autenticação biométrica, muito mais seguro do que um cartão físico roubado."
    },
    {
      "h2": "Cartões crypto virtuais vs carteira móvel: qual a diferença?",
      "p": "Um cartão crypto virtual e uma carteira crypto (MetaMask, Trust Wallet) são duas ferramentas complementares, não substituíveis. A carteira armazena os teus crypto-ativos on-chain com as tuas chaves privadas. O cartão virtual está ligado a uma conta emissora (custodial ou semi-custodial) e converte automaticamente as criptomoedas em moeda fiat no momento do pagamento — e esta conversão constitui um facto tributável em Portugal. A exceção notável é a MetaMask Card, que liga diretamente a carteira ao cartão, sem necessidade de conta intermediária. É a convergência mais avançada entre cartão virtual e carteira DeFi em ${YEAR}."
    },
    {
      "h2": "Como utilizar um cartão crypto virtual no dia a dia",
      "p": "Para compras online, o cartão virtual está pronto a usar mal seja ativado: introduz o número no formulário de pagamento, como qualquer Visa. Para compras em loja, adiciona-o ao Apple Pay ou Google Pay; o pagamento NFC funciona de imediato. Para recarregar, faz uma transferência SEPA a partir do teu banco (grátis, num dia útil) ou uma transferência crypto a partir da tua exchange. Dica de segurança: gera um número de cartão temporário para cada compra num site desconhecido, disponível na Crypto.com, Wirex ou Brighty através do menu 'cartão virtual' da app. Recorda que, em Portugal, os ganhos em crypto estão sujeitos a uma taxa de 28% se o ativo for detido há menos de 365 dias, sendo isentos após um ano; o Banco de Portugal e o enquadramento MiCA regulam os emissores que operam no mercado nacional."
    }
  ],
  "beginner": [
    {
      "h2": "Como começar com um cartão crypto sendo principiante?",
      "p": "O primeiro passo é escolher um cartão acessível sem staking e sem anuidade. Abre uma conta na plataforma, completa a verificação KYC (identidade e morada), depois recarrega o teu cartão a partir da tua exchange ou diretamente em euros por transferência SEPA. Para principiantes, evita plataformas com tokens proprietários voláteis; privilegia cartões associados a stablecoins (USDC) ou diretamente ao teu saldo em euros."
    },
    {
      "h2": "Melhores cartões crypto para principiantes em ${YEAR}: Revolut, Brighty, MetaMask",
      "p": "A Revolut combina banca tradicional e crypto numa única aplicação, ideal para principiantes que querem experimentar sem grandes compromissos. A Brighty é 100% grátis, com IBAN europeu e cashback em USDC sem staking. O MetaMask Card é perfeito se já estás familiarizado com carteiras Web3. Estas três opções têm um ponto em comum: registo rápido em menos de 10 minutos e utilização imediata desde o primeiro dia."
    },
    {
      "h2": "Os erros a evitar com o teu primeiro cartão crypto",
      "p": "Há várias armadilhas clássicas que aguardam os novos utilizadores. Primeira: escolher um cartão com base apenas na taxa de cashback apresentada, sem ter em conta os requisitos de staking e a volatilidade do token associado. Segunda: recarregar em crypto em cima da hora, o que expõe a atrasos nas transações e comissões de rede variáveis. Terceira: descurar as definições de segurança — ativa sempre o 2FA e as notificações de pagamento. Por fim, lê atentamente os limites mensais de cashback antes de contar com um ganho anual projetado."
    },
    {
      "h2": "Como entender a fiscalidade do teu cartão crypto desde o início?",
      "p": "Em Portugal, a utilização de um cartão crypto gera eventos fiscais a cada conversão de crypto em euros. Pagar com crypto é considerado uma alienação tributável: os ganhos obtidos em ativos detidos há menos de 365 dias estão sujeitos a uma taxa de 28% sobre as mais-valias, enquanto os ativos detidos por mais de um ano estão isentos de imposto, conforme as regras fiscais portuguesas e o enquadramento MiCA supervisionado pelo Banco de Portugal. Para um principiante, a recomendação mais simples é utilizar stablecoins (USDC, USDT) para recarregar o cartão: sem volatilidade, sem mais-valia realizada, sem imposto sobre a conversão. É a forma mais simples de aproveitar o cashback crypto sem as complicações fiscais associadas aos ativos voláteis."
    },
    {
      "h2": "Perguntas frequentes dos principiantes sobre cartões crypto",
      "p": "É possível usar um cartão crypto sem possuir crypto? Sim, podes recarregar em euros por transferência SEPA na Brighty ou na Revolut, sem nunca tocar em crypto. É necessária uma conta bancária para obter um cartão crypto? Não, alguns cartões (Brighty, MetaMask Card) funcionam sem banca tradicional. Quanto tempo demora a receber o cartão? A versão virtual fica disponível em menos de 5 minutos. A versão física é enviada entre 5 a 10 dias úteis, conforme o emissor. É possível gastar crypto diretamente ou é preciso converter? A conversão em euros é feita automaticamente no momento do pagamento, sem necessidade de qualquer intervenção manual."
    }
  ],
  "no-kyc": [
    {
      "h2": "Cartões crypto sem KYC: o que isto significa realmente",
      "p": "O termo \"sem KYC\" é frequentemente mal compreendido. Nenhum cartão Visa ou Mastercard é legalmente utilizável sem identificação — o regulamento MiCA e a diretiva AMLD5 exigem-no. O que se designa por \"cartões sem KYC\" são, na realidade, cartões com custódia reduzida: o Gnosis Pay liquida diretamente a partir do teu Gnosis Safe (wallet em self-custody), e o MetaMask Card funciona sem conta custodial centralizada. O KYC continua a ser obrigatório para a emissão do cartão, mas a tua crypto não transita por um intermediário centralizado."
    },
    {
      "h2": "Gnosis Pay e MetaMask Card: os cartões crypto mais próximos do modelo sem intermediário",
      "p": "O Gnosis Pay é o cartão on-chain mais avançado disponível: cada pagamento é assinado a partir do teu Gnosis Safe e liquidado em xDAI diretamente na blockchain. Nenhuma conta custodial, nenhum intermediário entre a tua wallet e o terminal de pagamento. O MetaMask Card segue o mesmo princípio: a tua crypto permanece na tua wallet até ao momento do pagamento, sem que a plataforma seja sua guardiã. Estes dois cartões representam a vanguarda da soberania financeira crypto em ${YEAR}."
    },
    {
      "h2": "Os limites da auto-custódia aplicada aos cartões de pagamento",
      "p": "Os cartões com custódia reduzida como o Gnosis Pay e o MetaMask Card apresentam vantagens inegáveis em termos de soberania, mas também condicionantes práticas. O carregamento exige domínio das wallets on-chain (gas fees, bridging, gestão de chaves). Em caso de perda das chaves privadas, o capital é irrecuperável — nenhum serviço de apoio ao cliente pode ajudar. A liquidez pode também ser limitada consoante a rede. Estes cartões são ideais para utilizadores DeFi experientes, sendo menos adequados para principiantes, que preferirão uma solução custodial como o Brighty ou o Nexo."
    },
    {
      "h2": "Segurança e auto-custódia: as boas práticas em ${YEAR}",
      "p": "Se utilizares um cartão crypto com custódia reduzida, algumas regras são imperativas. Em primeiro lugar, guarda a tua seed phrase (12 ou 24 palavras) offline, em papel ou numa placa de aço inoxidável — nunca na cloud nem em capturas de ecrã. Em segundo lugar, usa uma hardware wallet (Ledger, Trezor) como camada adicional de segurança. Em terceiro lugar, verifica sistematicamente os endereços de contrato antes de interagir com o teu Gnosis Safe ou com a tua wallet MetaMask. A auto-custódia oferece liberdade máxima, mas exige uma disciplina de segurança proporcional."
    },
    {
      "h2": "FAQ: cartões crypto e KYC, todas as respostas verdadeiras",
      "p": "É possível usar um cartão crypto sem fornecer documento de identificação? Não — qualquer cartão Visa ou Mastercard exige KYC legal, em conformidade com as regras do Banco de Portugal e do regulamento MiCA. O que se chama \"sem KYC\" significa \"sem conta custodial centralizada\", não sem identificação. O Gnosis Pay exige KYC? Sim, para a emissão do cartão, mas a tua crypto permanece na tua wallet. O MetaMask Card partilha os meus dados bancários? Não — o MetaMask Card não detém os teus fundos e a tua wallet mantém-se não-custodial. É possível pagar de forma anónima com um cartão crypto on-chain? As transações do Gnosis Pay são visíveis no explorador da Gnosis Chain, mas não estão publicamente associadas à tua identidade civil. Nota ainda que, em Portugal, pagar com crypto constitui uma alienação tributável: as mais-valias são tributadas a 28% se o ativo for detido há menos de 365 dias, sendo isentas após esse prazo."
    }
  ],
  "travel": [
    {
      "h2": "Qual o cartão crypto escolher para viajar para o estrangeiro?",
      "p": "Para viagens, três critérios são prioritários: a ausência de comissões de câmbio em moedas estrangeiras, levantamentos em caixas automáticos gratuitos no estrangeiro e aceitação mundial via Visa ou Mastercard. A Crypto.com oferece até 400€/mês de levantamentos gratuitos nos níveis superiores. A Bybit e a Nexo propõem igualmente vantagens de viagem com cashback em crypto em todas as compras no estrangeiro, independentemente da moeda local."
    },
    {
      "h2": "Comissões de câmbio e levantamentos em caixas automáticos com um cartão crypto",
      "p": "A maioria dos cartões crypto cobra 0% de comissões nas compras em moedas estrangeiras, uma vantagem significativa face aos cartões bancários tradicionais (1,5% a 3%). Em contrapartida, os levantamentos em caixas automáticos estão frequentemente limitados consoante o nível do cartão. Convém verificar o plafond mensal gratuito antes de partir: varia entre 200€ (níveis de entrada) e ilimitado (níveis premium) conforme os emitentes. Acima do plafond, aplicam-se geralmente comissões de 2%."
    },
    {
      "h2": "Seguros de viagem e vantagens premium dos cartões crypto",
      "p": "Os cartões crypto dos níveis superiores incluem frequentemente seguros de viagem integrados: os níveis Jade, Indigo e Obsidian da Crypto.com cobrem cancelamentos de voo, atrasos de bagagem e urgências médicas até 10 milhões de dólares. A Bybit Voyager e a Nexo oferecem proteções semelhantes. Estes seguros podem substituir o seguro de viagem anual tradicional (60 a 150€/ano), uma vantagem muitas vezes subestimada. Recomenda-se verificar as condições de cobertura (ativação do cartão, montante mínimo de transação) nos termos e condições antes de partir."
    },
    {
      "h2": "Qual o cartão mais indicado para cada tipo de viagem?",
      "p": "A escolha ideal depende do perfil de cada viajante. Para quem viaja com frequência (10 ou mais voos por ano), os níveis Jade ou Indigo da Crypto.com maximizam o valor com acesso a lounges Priority Pass, reembolso Airbnb e Expedia, e seguros de viagem completos. Para viajantes ocasionais, a Bybit ou a Nexo oferecem um bom cashback nas compras em moedas estrangeiras sem exigir um staking demasiado elevado. Para mochileiros e viajantes de longa duração, a Brighty ou a MetaMask Card são ideais: gratuitas, sem comissões FX, utilizáveis via Visa em todo o mundo, com cashback desde a primeira compra."
    },
    {
      "h2": "Conselhos práticos para utilizar o cartão crypto em viagem",
      "p": "Antes de partir: ative o cartão e efetue um primeiro pagamento em Portugal para confirmar o seu bom funcionamento. Registe o plafond mensal de levantamentos gratuitos em caixa automático do seu cartão. Em viagem: pague sempre em moeda local (recuse a conversão DCC proposta pelo comerciante, que custa entre 3% a 5% a mais). Mantenha um cartão bancário tradicional como alternativa. Em caso de problema: o apoio da Crypto.com e da Nexo está disponível 24h/24 via chat ao vivo. A MetaMask Card dispõe de um apoio comunitário no Discord bastante ativo. Tenha sempre uma pequena quantia em dinheiro local para situações de emergência. Atenção: em Portugal, o pagamento com crypto constitui uma alienação sujeita a imposto — as mais-valias são tributadas a 28% se o ativo for detido há menos de 365 dias, estando isentas após esse prazo, conforme as regras fiscais em vigor e a regulamentação MiCA supervisionada pelo Banco de Portugal."
    }
  ],
  "rewards": [
    {
      "h2": "Que recompensas valem mesmo a pena num cartão crypto?",
      "p": "O acesso a lounges de aeroporto custa cerca de 30 a 40€ por visita (preço diário Priority Pass). Se fizer 6 voos por ano, isso representa uma poupança anual de 180 a 240€. O Netflix oferecido equivale a 167€/ano, o Spotify a 120€/ano. Somando estas vantagens, um cartão Crypto.com Jade ou Bybit Voyager pode autofinanciar-se mesmo com encargos anuais moderados, desde que utilize realmente cada benefício."
    },
    {
      "h2": "Crypto.com, Nexo, Bybit: que recompensas para cada perfil?",
      "p": "A Crypto.com destaca-se para os grandes viajantes: lounges, reembolso Airbnb (10%), Expedia (10%), Netflix e Spotify. A Nexo oferece cashback em BTC ou NEXO em todas as compras, ideal para quem acumula. A Bybit propõe reembolsos semelhantes com um requisito de staking inferior. Para utilizadores do dia a dia sem viagens frequentes, a Gnosis Pay e a MetaMask Card otimizam o cashback puro sem vantagens lifestyle supérfluas."
    },
    {
      "h2": "Recompensas crypto vs. milhas aéreas: o que escolher?",
      "p": "A questão surge frequentemente entre os viajantes mais ativos. As milhas aéreas (programas Flying Blue, Miles & More) acumulam-se depressa, mas perdem valor se não forem usadas e estão sujeitas a datas de validade. O cashback em BTC ou ETH nunca expira e pode valorizar-se com o mercado. A Nexo e a Crypto.com permitem até acumular cashback crypto E vantagens de viagem em simultâneo. Se viajar na Europa com companhias low-cost, o cashback crypto é muitas vezes mais rentável do que milhas que não cobrem esses voos."
    },
    {
      "h2": "Como maximizar as recompensas com um cartão crypto?",
      "p": "Para tirar o máximo partido do seu cartão de recompensas, concentre todas as despesas recorrentes nesse cartão: subscrições (streaming, ginásio, software), compras de supermercado, restaurantes e transportes. Verifique se o seu cartão oferece taxas de cashback acrescidas em determinadas categorias — alguns cartões Crypto.com oferecem 10% de reembolso no Airbnb ou na Expedia. Carregue o cartão em crypto para evitar comissões de conversão e consulte regularmente o histórico de cashback para confirmar que as recompensas estão a ser creditadas corretamente."
    },
    {
      "h2": "As recompensas escondidas dos cartões crypto que talvez desconheça",
      "p": "Para além do cashback visível, muitos cartões oferecem vantagens pouco aproveitadas. A Crypto.com reembolsa até 100% da subscrição CRO Arena (anteriormente Staples Center). A Nexo oferece rendimentos adicionais sobre os ativos depositados, acumuláveis com o cashback do cartão. A Bybit propõe aumentos pontuais de cashback durante campanhas (duplicação temporária da taxa em certas categorias). A Bitpanda dá acesso a NFT exclusivos e sorteios para utilizadores ativos. Consulte regularmente a secção de recompensas da sua aplicação — as promoções são frequentemente temporárias e não são notificadas por e-mail."
    }
  ],
  "physical": [
    {
      "h2": "Cartão crypto físico vs virtual: quais as diferenças concretas?",
      "p": "O cartão físico distingue-se por três vantagens principais: o acesso a levantamentos de numerário (impossível com um cartão puramente virtual), a utilização em todos os comerciantes que aceitam Visa/Mastercard sem necessidade de smartphone, e uma segurança reforçada, uma vez que o número do cartão virtual fica protegido. Em contrapartida, a entrega demora 1 a 2 semanas consoante o país, ao contrário da ativação instantânea do cartão virtual. Os dois formatos são complementares: a maioria dos emissores disponibiliza ambos com uma única conta, permitindo escolher conforme o contexto."
    },
    {
      "h2": "Crypto.com, Revolut, Nexo, Bybit: melhores cartões físicos ${YEAR}",
      "p": "A Crypto.com oferece um cartão Visa físico disponível em 5 níveis (Ruby, Jade, Indigo, Frosted Rose, Obsidian) com cashback de 1% a 8% consoante o staking em CRO. A Revolut disponibiliza um cartão físico grátis (nível Standard) com vantagens bancárias completas a partir da versão premium. A Nexo fornece um cartão Mastercard físico com cashback em BTC ou NEXO, sem staking obrigatório. A Bybit oferece um cartão Visa físico com cashback em BIT e plafonds de levantamento em ATM vantajosos para quem viaja com frequência."
    },
    {
      "h2": "Entrega e segurança do cartão crypto físico",
      "p": "A entrega de um cartão físico demora geralmente entre 7 a 15 dias úteis na Europa, dependendo do país e do prestador logístico do emissor. A Crypto.com envia para todo o mundo com rastreio de encomenda. A Revolut e a Nexo entregam na UE entre 5 a 10 dias. Assim que receber o cartão, ative-o imediatamente na aplicação e ative o 2FA. Em caso de perda ou roubo, bloqueie o cartão de imediato a partir da aplicação — a maioria dos emissores permite o bloqueio instantâneo sem encerrar a conta. O cartão de substituição é geralmente enviado no prazo de 10 dias."
    },
    {
      "h2": "Cartão crypto físico no estrangeiro: ATM, aceitação e conselhos",
      "p": "Os cartões crypto físicos são particularmente indicados para viagens. Visa e Mastercard são aceites na quase totalidade dos comércios e ATM internacionais. Verifique o seu plafond mensal de levantamento gratuito antes de partir — a maioria dos cartões de entrada de gama oferece entre 200 a 400 € grátis, e os níveis premium até 800 € ou ilimitado. Informe o emissor sobre viagens prolongadas para evitar bloqueios de transação. Em países com fraca infraestrutura bancária, tenha sempre numerário local como alternativa de segurança."
    },
    {
      "h2": "Quando optar por um cartão crypto físico em vez do virtual?",
      "p": "O cartão físico impõe-se em três situações principais: levantamentos em ATM (o cartão virtual não funciona em caixas automáticos), comércios que não aceitam Apple Pay ou Google Pay (raros, mas existentes, sobretudo em zonas rurais ou em certos países), e viagens para regiões com conectividade limitada onde não é possível depender do smartphone. O cartão virtual é preferível para todas as compras online, subscrições e países onde o pagamento por aproximação é universal. Em Portugal, importa também considerar a fiscalidade: ao pagar com crypto efetua uma alienação sujeita a imposto — as mais-valias são tributadas a 28% se o ativo for detido há menos de 365 dias, ficando isentas após um ano, em conformidade com as regras aplicáveis e enquadradas no regime MiCA supervisionado pelo Banco de Portugal. A estratégia ideal em ${YEAR}: ative o cartão virtual imediatamente após o KYC, utilize-o no dia a dia, e solicite o cartão físico apenas se tiver uma necessidade concreta — a entrega demora sempre 1 a 2 semanas."
    }
  ],
  "belgium": [
    {
      "h2": "Que cartões crypto estão disponíveis para residentes em Portugal?",
      "p": "Os residentes em Portugal têm acesso aos mesmos cartões crypto que os restantes cidadãos europeus, graças ao passaporte EEE conferido pelo regulamento MiCA. Crypto.com Visa, Revolut, Nexo Card, Gnosis Pay, MetaMask Card, Bybit Card e Brighty estão todas disponíveis para utilizadores em Portugal. O Banco de Portugal supervisiona os prestadores de serviços em criptoativos em Portugal e exige o cumprimento das normas MiCA por parte de qualquer operador ativo no mercado português."
    },
    {
      "h2": "Fiscalidade das criptomoedas em Portugal: o que os utilizadores precisam de saber",
      "p": "Em Portugal, a fiscalidade das criptomoedas depende do período de detenção dos ativos. As mais-valias obtidas com criptoativos detidos por menos de 365 dias são tributadas a 28%. Após um ano de detenção, as mais-valias ficam isentas de imposto. Cada pagamento efetuado com um cartão crypto desencadeia tecnicamente uma alienação do ativo, potencialmente sujeita a tributação se o período de detenção for inferior a um ano. Consulte um contabilista certificado para uma análise personalizada da sua situação."
    },
    {
      "h2": "Cartão crypto em Portugal: Gnosis Pay e MetaMask Card em destaque",
      "p": "Para os residentes em Portugal, o Gnosis Pay distingue-se pelo seu modelo on-chain único: cada pagamento é liquidado diretamente a partir da tua Gnosis Safe em xDAI, sem qualquer intermediário centralizado. A MetaMask Card oferece uma alternativa DeFi-native com cashback em ETH. Para quem pretende um cashback mais elevado, o Crypto.com Jade (3%) ou o Nexo Card (em BTC) são excelentes opções disponíveis em Portugal. Todos estes cartões são Visa ou Mastercard, aceites em todo o território nacional e no estrangeiro."
    },
    {
      "h2": "Melhor cashback crypto para residentes em Portugal em ${YEAR}",
      "p": "Em Portugal, a classificação dos cartões por cashback real é a seguinte: Crypto.com Jade (3% em CRO, staking obrigatório), Nexo Card (2% em BTC ou NEXO, sem staking), Gnosis Pay (2% em GNO, on-chain, sem staking), Bitpanda Card (2% em BEST), Brighty (1,75% em USDC, sem staking). Para os residentes em Portugal que pretendem maximizar o retorno sem imobilizar capital, o Nexo Card e o Gnosis Pay oferecem a melhor relação rendimento/risco. O cashback em BTC (Nexo) é particularmente relevante num contexto de mercado em alta, ao passo que o cashback em USDC (Brighty) é mais estável e previsível para uma gestão prudente."
    },
    {
      "h2": "Como abrir um cartão crypto a partir de Portugal: guia passo a passo",
      "p": "Abrir um cartão crypto a partir de Portugal é simples. (1) Escolhe o emissor de acordo com o teu perfil: Gnosis Pay para DeFi, Nexo para cashback em BTC, Brighty para maior simplicidade. (2) Descarrega a aplicação oficial e cria a tua conta. (3) KYC: fotografa o teu cartão de cidadão ou passaporte português e tira uma selfie. Prazo: 5 a 30 minutos. (4) Ativa o teu cartão virtual imediatamente após a validação do KYC. (5) Recarrega por transferência SEPA a partir do teu banco português (Caixa Geral de Depósitos, Millennium BCP, Novo Banco, Santander Portugal). (6) Adiciona o cartão ao Apple Pay ou ao Google Pay para pagar em qualquer lugar, em Portugal e no estrangeiro."
    }
  ],
  "austria": [
    {
      "h2": "Que cartões crypto estão disponíveis para residentes em Portugal?",
      "p": "Os residentes em Portugal têm acesso completo aos cartões crypto regulados ao abrigo do MiCA no mercado europeu. A Crypto.com Visa, a Nexo Card, a Gnosis Pay, a MetaMask Card e a Revolut estão todas disponíveis em Portugal. O Banco de Portugal é a autoridade de supervisão do sector financeiro nacional, enquanto o regime MiCA estabelece o enquadramento regulatório europeu para os emissores de cartões crypto. Para os residentes portugueses que procuram uma solução integrada, as opções internacionais reguladas pelo MiCA representam a escolha mais segura e acessível."
    },
    {
      "h2": "Fiscalidade das criptomoedas em Portugal: isenção após um ano e taxa de 28%",
      "p": "Portugal aplica um regime fiscal claro para as criptomoedas: as mais-valias resultantes da venda de cripto detida por menos de 365 dias são tributadas a uma taxa autónoma de 28%; após um ano de detenção, as mais-valias ficam isentas de imposto. Pagar com um cartão crypto constitui uma alienação tributável, independentemente do período de detenção, pelo que cada utilização de um cartão com activos voláteis pode gerar um facto gerador de imposto. A estratégia mais simples consiste em recarregar o cartão com stablecoins, evitando assim qualquer evento fiscal no momento do pagamento. A Autoridade Tributária e Aduaneira (AT) é responsável pela fiscalização deste regime."
    },
    {
      "h2": "Crypto.com Visa, Nexo Card e Gnosis Pay: as principais opções em Portugal",
      "p": "Sem uma plataforma de origem nacional com o mesmo nível de integração local, os residentes em Portugal orientam-se naturalmente para as principais opções europeias reguladas pelo MiCA. A Crypto.com Visa, a Nexo Card e a Gnosis Pay destacam-se pela disponibilidade em Portugal, pelo suporte a SEPA e pela conformidade regulatória europeia. Todas permitem converter activos crypto no momento do pagamento, com conversão automática e emissão de cartão Visa ou Mastercard para uso quotidiano. O Banco de Portugal acompanha a implementação do MiCA a nível nacional."
    },
    {
      "h2": "Melhor cashback crypto para residentes em Portugal em ${YEAR}",
      "p": "Em Portugal, a classificação dos cartões por cashback real é a seguinte: Crypto.com Jade (3% em CRO, requer staking), Nexo Card (2% em BTC ou NEXO, sem staking), Gnosis Pay (2% em GNO, on-chain), Brighty (1,75% em USDC, sem staking). Para quem pretende o melhor cashback sem qualquer requisito de staking, a Nexo Card é a opção mais vantajosa. A Gnosis Pay distingue-se pela abordagem totalmente on-chain. A Brighty é a mais simples de activar para quem começa. Importa recordar que o cashback recebido em cripto pode ser considerado rendimento tributável; recomenda-se consultar um contabilista familiarizado com o regime fiscal português."
    },
    {
      "h2": "Como abrir um cartão crypto em Portugal: guia prático",
      "p": "Abrir um cartão crypto em Portugal segue o mesmo processo que nos restantes países abrangidos pelo MiCA. (1) Escolha o emissor: Nexo, Gnosis Pay, Crypto.com ou outro operador regulado disponível em Portugal. (2) Descarregue a aplicação do emissor escolhido e crie a sua conta. (3) KYC: documento de identificação português (Cartão de Cidadão ou Passaporte) e selfie. Prazo habitual: entre 5 e 60 minutos. (4) Recarregue via transferência SEPA a partir do seu banco português (CGD, Millennium BCP, Novo Banco, Santander, BPI). (5) Nota fiscal: cada pagamento efectuado com activos voláteis pode constituir uma alienação tributável; se detidos há menos de 365 dias, aplica-se a taxa de 28%. Utilize stablecoins para recarregar e evitar qualquer evento fiscal no momento do pagamento."
    }
  ],
  "iban": [
    {
      "h2": "O que é um cartão crypto com IBAN?",
      "p": "Um cartão crypto com IBAN combina as funcionalidades de uma conta bancária tradicional com as vantagens das criptomoedas. O IBAN (International Bank Account Number) permite receber transferências bancárias, salários e pagamentos SEPA, tal como uma conta à ordem convencional. A diferença está no facto de o dinheiro ser gerido em ligação com criptomoedas, sendo que cada compra com o cartão gera cashback em crypto. Em Portugal, a oferta de neobancas crypto com IBAN português e supervisão do Banco de Portugal ainda é limitada; a maioria dos emissores opera ao abrigo do enquadramento MiCA, o que significa que o IBAN pode ser de outro país da União Europeia, mas continua a ser utilizável para domiciliar o salário ou débitos diretos."
    },
    {
      "h2": "Deblock, Brighty, Revolut: qual o cartão IBAN a escolher em ${YEAR}?",
      "p": "Os principais cartões crypto com IBAN em ${YEAR}: Deblock (IBAN FR, regulado ACPR, cashback de 1% no plano Premium a 9,90 €/mês), Brighty (IBAN EU, regulado FINMA, cashback em USDC), Revolut (IBAN local consoante o país, cashback em crypto nos planos Premium). Para utilizadores em Portugal, nenhum destes emissores oferece atualmente um IBAN PT, pelo que a domiciliação de salário pode exigir confirmação junto da entidade patronal. O Brighty é ideal para quem pretende uma conta crypto com transferências internacionais. O Revolut oferece o ecossistema mais completo, embora as funcionalidades crypto sejam limitadas no plano base."
    },
    {
      "h2": "Fiscalidade dos levantamentos e transferências SEPA: o que é preciso saber",
      "p": "Com um cartão crypto com IBAN, as transferências SEPA em euros não desencadeiam qualquer tributação por si só. Contudo, se recarregar a conta IBAN convertendo criptomoedas em euros, essa conversão constitui uma alienação sujeita a imposto em Portugal: as mais-valias são tributadas a 28% se os ativos forem detidos há menos de 365 dias, sendo isentas após esse prazo. Além disso, pagar com crypto utilizando o cartão é igualmente considerado uma alienação tributável. Algumas carteiras, como as do Deblock, permitem manter um saldo em euros separado da carteira crypto, o que pode simplificar a gestão fiscal. Consulte um consultor fiscal para a sua situação pessoal, uma vez que as regras dependem da forma como cada cartão gere a conversão crypto/euro."
    }
  ]
};

export const THEME_FAQ_PT: Record<string, { q: string; a: string }[]> = {
  "2026": [
    {
      "q": "Qual é o melhor cartão crypto em ${YEAR}?",
      "a": "Em ${YEAR}, o Gnosis Pay e o MetaMask Card destacam-se para o dia a dia (sem staking, sem comissões). Para o máximo de cashback, o Crypto.com Obsidian continua a ser a referência, apesar do staking elevado."
    },
    {
      "q": "Os cartões crypto são seguros em ${YEAR}?",
      "a": "Sim, graças ao regulamento MiCA em vigor em toda a UE desde 2025. Os emitentes estão regulados e supervisionados, estando os teus fundos mais protegidos do que anteriormente."
    },
    {
      "q": "Existem novos cartões crypto em ${YEAR}?",
      "a": "Sim, vários novos operadores entraram no mercado na sequência da adoção do regulamento MiCA. O nosso comparativo é atualizado regularmente para refletir as últimas ofertas disponíveis."
    },
    {
      "q": "O cashback dos cartões crypto é tributável em ${YEAR}?",
      "a": "Em Portugal, as mais-valias em criptoativos estão sujeitas a uma taxa de 28% se os ativos forem detidos há menos de 365 dias. Após um ano de detenção, os ganhos estão isentos de imposto. O pagamento com criptoativos constitui igualmente um facto tributável. Consulta um contabilista certificado para a tua situação pessoal."
    },
    {
      "q": "Qual o cartão crypto a escolher para Portugal em ${YEAR}?",
      "a": "O Gnosis Pay e o Crypto.com estão confirmados como disponíveis em Portugal. Dá preferência a um cartão emitido por um prestador de serviços de criptoativos registado junto do Banco de Portugal, ao abrigo do regulamento MiCA, para uma proteção máxima."
    }
  ],
  "best": [
    {
      "q": "Qual é o melhor cartão crypto em ${YEAR}?",
      "a": "Em ${YEAR}, os melhores cartões crypto são o Crypto.com Obsidian (8% de cashback), o Gnosis Pay (2% sem staking) e o MetaMask Card (1% com self-custody). A melhor escolha depende do teu perfil."
    },
    {
      "q": "Os cartões crypto são seguros?",
      "a": "Sim, desde que se escolha um cartão emitido por um emitente regulado registado junto do Banco de Portugal ou de outros reguladores europeus reconhecidos ao abrigo do regulamento MiCA."
    },
    {
      "q": "É possível utilizar um cartão crypto em todo o mundo?",
      "a": "Sim, os cartões crypto Visa e Mastercard são aceites em todo o mundo onde estas redes estão presentes, ou seja, em mais de 50 milhões de pontos de venda."
    },
    {
      "q": "O cashback dos cartões crypto é tributável em Portugal?",
      "a": "Em Portugal, o cashback em criptomoeda pode constituir um rendimento sujeito a imposto. Quanto aos ganhos obtidos com a posterior venda, estão sujeitos a uma taxa de 28% se os ativos forem detidos há menos de 365 dias; após um ano de detenção, os ganhos ficam isentos de imposto. Note-se ainda que pagar com crypto equivale a uma alienação e pode gerar um facto tributável."
    },
    {
      "q": "É necessário fazer staking para obter cashback?",
      "a": "Não, vários cartões oferecem cashback sem staking obrigatório: Gnosis Pay, MetaMask Card e Brighty. Os cartões com staking oferecem taxas mais elevadas, mas exigem que os fundos fiquem imobilizados."
    }
  ],
  "cashback": [
    {
      "q": "Qual o cartão crypto que oferece o cashback mais elevado?",
      "a": "O Crypto.com Obsidian oferece até 8%, mas exige 400 000 CRO em staking. O Gnosis Pay oferece 2% sem staking, sendo muitas vezes mais rentável."
    },
    {
      "q": "O cashback é pago em crypto ou em euros?",
      "a": "O cashback é geralmente creditado na criptomoeda nativa da plataforma (CRO, etc.) ou em stablecoin."
    },
    {
      "q": "Como calcular a rentabilidade real do cashback?",
      "a": "Se gastar 1000€/mês e fizer staking de 5000€ para obter 3% de cashback, recebe 360€/ano, mas arrisca uma desvalorização sobre os 5000€ detidos em staking."
    },
    {
      "q": "É possível combinar vários cartões crypto?",
      "a": "Sim, alguns utilizadores combinam um cartão premium com um cartão grátis para maximizar o cashback."
    },
    {
      "q": "Existe um limite de cashback?",
      "a": "Sim, a maioria dos cartões impõe um limite mensal ou anual. Alguns limitam o cashback a 50€/mês."
    }
  ],
  "no-fees": [
    {
      "q": "Existem cartões crypto verdadeiramente grátis?",
      "a": "Sim: MetaMask Card, Gnosis Pay, Brighty. Sem taxas de emissão nem de subscrição."
    },
    {
      "q": "Um cartão crypto grátis é pior?",
      "a": "Não. Alguns cartões grátis oferecem melhor cashback do que cartões pagos."
    },
    {
      "q": "Existem comissões ocultas nos cartões 'grátis'?",
      "a": "As comissões ocultas mais comuns são: comissões de câmbio (FX), comissões em ATM acima de um determinado limite e comissões de inatividade."
    },
    {
      "q": "É possível fazer levantamentos em dinheiro sem custos?",
      "a": "A maioria permite levantamentos grátis entre 200€ e 400€ por mês. Acima desse valor, aplicam-se comissões de 1% a 2%."
    },
    {
      "q": "Os cartões grátis têm os mesmos limites de pagamento?",
      "a": "Geralmente, os cartões grátis têm um limite diário entre 2000€ e 10 000€."
    }
  ],
  "no-staking": [
    {
      "q": "O que é o staking num cartão crypto?",
      "a": "Bloquear uma quantidade de crypto para desbloquear vantagens (cashback mais elevado, etc.). Este capital fica imobilizado."
    },
    {
      "q": "Porquê evitar o staking?",
      "a": "O staking expõe o capital à volatilidade. Sem staking, o capital fica disponível a qualquer momento."
    },
    {
      "q": "Os cartões sem staking têm bom cashback?",
      "a": "Sim: Gnosis Pay (2%), MetaMask Card (1%), Brighty (até 4%)."
    },
    {
      "q": "Qual a diferença entre staking e depósito mínimo?",
      "a": "O staking bloqueia cryptos na blockchain (com risco de perda). Um depósito mínimo é diferente: os fundos ficam geralmente disponíveis para levantamento."
    },
    {
      "q": "É possível mudar para um cartão com staking mais tarde?",
      "a": "Sim, a maioria das plataformas permite evoluir para um nível superior posteriormente."
    }
  ],
  "france": [
    {
      "q": "Quais são os cartões crypto disponíveis em Portugal?",
      "a": "Os principais: Crypto.com, Gnosis Pay, MetaMask Card, Brighty, Bleap e Wirex."
    },
    {
      "q": "Os cartões crypto são legais em Portugal?",
      "a": "Sim. Os emitentes devem estar registados junto do Banco de Portugal como prestadores de serviços de ativos virtuais (PSAV), no quadro do regulamento MiCA."
    },
    {
      "q": "É necessário declarar o cartão crypto ao fisco em Portugal?",
      "a": "Sim. As contas e ativos virtuais detidos no estrangeiro devem ser declarados no Anexo L do IRS. As mais-valias estão sujeitas a uma taxa autónoma de 28% se os ativos forem detidos há menos de 365 dias; após um ano de detenção, as mais-valias ficam isentas de imposto. O pagamento com crypto é considerado uma alienação tributável, pelo que pode gerar mais-valias a declarar."
    },
    {
      "q": "É possível pagar impostos com um cartão crypto em Portugal?",
      "a": "Não, a Autoridade Tributária e Aduaneira não aceita o pagamento de impostos diretamente em criptomoedas."
    },
    {
      "q": "Qual o cartão com melhor suporte em português?",
      "a": "A Crypto.com dispõe de suporte em português. A Gnosis Pay e a MetaMask Card têm suporte principalmente em inglês."
    }
  ],
  "virtual": [
    {
      "q": "O que é um cartão crypto virtual?",
      "a": "Um cartão de pagamento digital ligado à sua carteira crypto, utilizável online e através do Apple Pay/Google Pay, sem suporte físico."
    },
    {
      "q": "Como obter um cartão crypto virtual?",
      "a": "Descarregue a aplicação, complete o KYC, e o cartão fica disponível em poucos minutos."
    },
    {
      "q": "É possível fazer levantamentos com um cartão virtual?",
      "a": "Não, os cartões puramente virtuais não permitem levantamentos em ATM."
    },
    {
      "q": "Um cartão virtual é igualmente seguro?",
      "a": "Sim, muitas vezes mais: não pode ser alvo de skimming. Alguns geram um novo número por cada transação."
    },
    {
      "q": "Os cartões virtuais são compatíveis com o Apple Pay?",
      "a": "Sim, a maioria é compatível com o Apple Pay e o Google Pay."
    }
  ],
  "beginner": [
    {
      "q": "Por onde começar quando se é principiante?",
      "a": "Gnosis Pay ou MetaMask Card: sem staking, sem comissões, interface simples, cashback imediato."
    },
    {
      "q": "É preciso perceber de cripto para usar um cartão cripto?",
      "a": "Não, funcionam como um cartão bancário normal. Carrega-se a partir de uma exchange e paga-se em qualquer lugar."
    },
    {
      "q": "Qual é o principal risco para um principiante?",
      "a": "A volatilidade: se a cripto no cartão descer, perde-se poder de compra. Recomenda-se o uso de stablecoins (USDC)."
    },
    {
      "q": "Qual o depósito mínimo necessário?",
      "a": "A maioria não impõe qualquer mínimo. Comece com 50-100€ para testar."
    },
    {
      "q": "Como se recarrega um cartão cripto?",
      "a": "Através da app, transfere-se cripto a partir da sua exchange. A conversão para euros é feita automaticamente."
    }
  ],
  "no-kyc": [
    {
      "q": "Existem mesmo cartões crypto sem KYC?",
      "a": "Não em sentido estrito: nenhum cartão crypto regulamentado na Europa permite uma utilização totalmente anónima. Mas cartões como o MetaMask Card ou o Gnosis Pay propõem um KYC mínimo através da tua wallet Web3."
    },
    {
      "q": "O que é o KYC para um cartão crypto?",
      "a": "Know Your Customer: a verificação obrigatória de identidade (documento de identificação, morada). Exigido pela regulamentação AML em vigor na Europa para combater o branqueamento de capitais."
    },
    {
      "q": "Por que razão alguns cartões têm menos KYC?",
      "a": "Os cartões baseados em wallets self-custody (MetaMask, Gnosis) descentralizam a custódia dos fundos, o que permite um processo KYC simplificado mantendo-se em conformidade com a legislação em vigor."
    },
    {
      "q": "É possível pagar anonimamente com um cartão crypto?",
      "a": "Não na Europa. O regulamento MiCA e as diretivas AML impõem uma identificação mínima. No entanto, os dados crypto não são expostos aos comerciantes no momento do pagamento."
    },
    {
      "q": "Qual é o cartão crypto com menos KYC em ${YEAR}?",
      "a": "O MetaMask Card e o Gnosis Pay são os que apresentam o processo de registo mais simples, graças à sua arquitetura descentralizada e ao modelo self-custody."
    }
  ],
  "travel": [
    {
      "q": "Os cartões crypto têm comissões de câmbio no estrangeiro?",
      "a": "A maioria dos cartões crypto não aplica comissões de câmbio em despesas em moeda estrangeira, ao contrário dos cartões bancários tradicionais (1-3% de comissões)."
    },
    {
      "q": "É possível fazer levantamentos de dinheiro no estrangeiro com um cartão crypto?",
      "a": "Sim, a maioria oferece levantamentos em ATM gratuitos até um limite mensal (200-400€). Acima desse limite, aplicam-se comissões de 1-2%."
    },
    {
      "q": "Um cartão crypto é aceite em todo o mundo?",
      "a": "Sim, os cartões Visa e Mastercard são aceites em mais de 200 países e territórios, em mais de 50 milhões de pontos de venda."
    },
    {
      "q": "É necessário avisar o banco crypto antes de viajar?",
      "a": "Não, ao contrário dos bancos tradicionais, os cartões crypto geralmente não precisam de ser notificados antes de uma viagem ao estrangeiro."
    },
    {
      "q": "Qual é o melhor cartão crypto para viajar?",
      "a": "O Crypto.com oferece as melhores vantagens de viagem (lounges, seguro de viagem). Para um orçamento mais reduzido, o MetaMask Card ou o Gnosis Pay são ideais, sem comissões anuais."
    }
  ],
  "rewards": [
    {
      "q": "Quais são as vantagens de recompensas dos cartões crypto premium?",
      "a": "As principais recompensas incluem: cashback em crypto (1-8%), acesso a lounges de aeroporto, reembolso de subscrições Netflix/Spotify, seguro de viagem e cashback adicional em determinadas plataformas."
    },
    {
      "q": "As vantagens de recompensas valem mesmo a pena?",
      "a": "Depende: para um utilizador ativo que gaste 2 000€/mês, um cashback de 2% equivale a 480€/ano. Convém comparar com o custo do staking necessário para atingir esse nível."
    },
    {
      "q": "É possível acumular várias recompensas num único cartão crypto?",
      "a": "Sim, alguns cartões permitem acumular cashback + lounge + reembolsos de subscrições. O Crypto.com Obsidian é o campeão desta categoria."
    },
    {
      "q": "As recompensas em crypto são tributáveis em Portugal?",
      "a": "Em Portugal, as recompensas em crypto podem ser consideradas rendimentos sujeitos a imposto. Caso sejam posteriormente alienadas, aplicam-se as regras do IRS: os ganhos são tributados a 28% se o ativo for detido há menos de 365 dias, sendo isentos após um ano de detenção. A utilização de crypto para pagar bens ou serviços constitui igualmente uma alienação fiscal sujeita a tributação. Recomenda-se consultar um contabilista certificado e acompanhar as orientações do regulador, designadamente no âmbito do quadro MiCA supervisionado pelo Banco de Portugal."
    },
    {
      "q": "Como maximizar as recompensas com um cartão crypto?",
      "a": "Utiliza o cartão para todas as despesas correntes, aproveita os reembolsos de subscrições e escolhe um nível de staking adequado ao teu perfil de utilização e capacidade financeira."
    }
  ],
  "physical": [
    {
      "q": "Como receber um cartão crypto físico?",
      "a": "Após o registo e validação KYC, encomenda o cartão através da aplicação. A entrega demora entre 5 a 15 dias úteis, consoante o país e o nível de cartão escolhido. O cartão Crypto.com é grátis a partir do nível Ruby Steel."
    },
    {
      "q": "O cartão crypto físico funciona no estrangeiro?",
      "a": "Sim, os cartões Visa e Mastercard são aceites em mais de 200 países. A maioria dos cartões crypto não aplica comissões de câmbio nas despesas em moeda estrangeira."
    },
    {
      "q": "É possível fazer levantamentos em dinheiro com um cartão crypto físico?",
      "a": "Sim, essa é a principal vantagem em relação a um cartão virtual. Os limites de levantamento em Multibanco variam entre 200€/mês (entrada de gama) e ilimitados (nível premium)."
    },
    {
      "q": "O cartão físico é mais seguro do que um cartão virtual?",
      "a": "Os dois têm características distintas: o cartão virtual não pode ser alvo de skimming e gera números únicos para cada transação. O físico é protegido pelo código PIN e pode ser bloqueado instantaneamente através da aplicação."
    },
    {
      "q": "Quanto tempo demora a entrega de um cartão crypto físico?",
      "a": "Em Portugal, prevê-se entre 5 a 10 dias úteis. A Crypto.com, a Nexo e a Bybit oferecem entrega grátis. Alguns emissores cobram comissões de substituição (5–10€) em caso de perda ou roubo."
    }
  ],
  "belgium": [
    {
      "q": "Quais são os cartões crypto disponíveis em Portugal?",
      "a": "Em ${YEAR}, os principais cartões crypto disponíveis em Portugal são: Bybit Card, Crypto.com Visa, Nexo Card, Gnosis Pay, Brighty, MetaMask Card e Wirex. Portugal faz parte do EEE e beneficia do enquadramento MiCA."
    },
    {
      "q": "Os cartões crypto são legais em Portugal?",
      "a": "Sim. Desde a entrada em vigor do MiCA em 2024, os emitentes de cartões crypto operam sob licença europeia unificada. O Banco de Portugal supervisiona a conformidade local e assegura a aplicação do regulamento no território nacional."
    },
    {
      "q": "É necessário declarar um cartão crypto ao fisco em Portugal?",
      "a": "Sim. As contas detidas junto de instituições estrangeiras devem ser declaradas à Autoridade Tributária e Aduaneira (AT) na declaração de IRS. Em Portugal, as mais-valias em criptoativos estão sujeitas a uma taxa autónoma de 28% caso os ativos sejam detidos há menos de 365 dias; após um ano de detenção, as mais-valias ficam isentas de tributação. O pagamento de bens ou serviços com crypto é considerado uma alienação onerosa e constitui um facto tributável."
    },
    {
      "q": "Existem restrições específicas em Portugal para os cartões crypto?",
      "a": "Portugal, enquanto Estado-Membro sujeito ao MiCA, aplica regras estritas em matéria de comunicação comercial e publicidade de criptoativos. Algumas ofertas promocionais de cashback podem estar limitadas ou apresentar condições diferentes das versões disponíveis noutros mercados europeus."
    },
    {
      "q": "Qual é o melhor cartão crypto para um residente em Portugal?",
      "a": "A Bybit Card (até 10% de cashback sem necessidade de staking) e a Gnosis Pay (5% em GNO, em self-custody) são as melhores opções para residentes em Portugal que procuram um bom cashback sem obrigações de staking."
    }
  ],
  "austria": [
    {
      "q": "Quais cartões crypto estão disponíveis em Portugal?",
      "a": "Em ${YEAR}, os principais cartões crypto disponíveis em Portugal são: Bybit Card, Crypto.com Visa, Nexo Card, Gnosis Pay, Trade Republic e Brighty. A oferta tem crescido significativamente com a adoção do enquadramento MiCA na União Europeia."
    },
    {
      "q": "Os cartões crypto são legais em Portugal?",
      "a": "Sim. O Banco de Portugal regula os serviços crypto em Portugal. Desde a entrada em vigor do MiCA, os emitentes operam sob passaporte europeu unificado, o que facilita o acesso a cartões de emitentes de outros Estados-Membros."
    },
    {
      "q": "É necessário declarar um cartão crypto ao fisco português?",
      "a": "Sim. Em Portugal, os ganhos com crypto estão sujeitos a uma taxa autónoma de 28% se os ativos forem detidos há menos de 365 dias. Após um ano de detenção, os ganhos estão isentos de imposto. O pagamento de bens ou serviços com crypto é considerado uma alienação tributável, podendo gerar mais-valias a declarar no IRS. Consulta um consultor fiscal para a tua situação específica."
    },
    {
      "q": "A Crypto.com Visa é a melhor opção em Portugal?",
      "a": "A Crypto.com Visa é uma das mais populares em Portugal, oferecendo cashback em CRO e benefícios como subscrições grátis de serviços de streaming, mediante staking. No entanto, cartões como a Bybit Card (até 10% de cashback sem staking obrigatório) ou a Nexo Card podem ser mais vantajosos consoante o perfil de utilização."
    },
    {
      "q": "Qual é o melhor cartão crypto para um residente em Portugal?",
      "a": "A Bybit Card (até 10% de cashback sem staking obrigatório), a Crypto.com Visa (benefícios premium com staking) e a Trade Republic (1% em ETF para poupança automática) cobrem os três perfis principais em Portugal. A escolha ideal depende do volume de gastos, da tolerância ao staking e da estratégia de levantamento de fundos."
    }
  ],
  "iban": [
    {
      "q": "O que é um cartão crypto com IBAN?",
      "a": "Um cartão crypto com IBAN integra uma conta bancária IBAN europeia (SEPA) diretamente ligada aos teus ativos crypto. Em ${YEAR}, a Brighty, a Deblock e a Gnosis Pay oferecem este tipo de conta, permitindo receber salário, fazer transferências SEPA e utilizar um cartão Visa/Mastercard crypto."
    },
    {
      "q": "Qual o cartão crypto que oferece um IBAN em ${YEAR}?",
      "a": "Em ${YEAR}, as melhores opções são: Brighty (IBAN CH, transferências SEPA grátis), Deblock (IBAN FR, integração DeFi), Gnosis Pay (conta on-chain com IBAN) e Revolut (IBAN EU com opção crypto). A Brighty é particularmente adequada para residentes em Portugal."
    },
    {
      "q": "Um IBAN crypto é seguro?",
      "a": "Sim, desde que se escolha um emissor regulado ao abrigo do MiCA ou licenciado como EMI (instituição de moeda eletrónica). A Brighty é supervisionada pela FINMA (Suíça) e a Deblock opera sob supervisão equivalente na União Europeia. Os fundos estão segregados do operador, sendo fiscalizados no quadro do Banco de Portugal para entidades com passaporte europeu ativo em Portugal."
    },
    {
      "q": "É possível receber o salário numa conta com IBAN crypto?",
      "a": "Sim. A Brighty e a Deblock aceitam transferências SEPA a crédito (salários, reembolsos). Depois, é possível converter para crypto ou pagar diretamente com o cartão."
    },
    {
      "q": "Qual a diferença entre um IBAN crypto e uma conta bancária tradicional?",
      "a": "Um IBAN crypto permite gerir cryptos e euros no mesmo lugar, frequentemente com comissões de conversão mais baixas (0–0,5%) e acesso a DeFi. No entanto, não beneficia da garantia de depósitos do Fundo de Garantia de Depósitos (FGD), que cobre até 100 000 € nas contas de bancos tradicionais supervisionados pelo Banco de Portugal."
    }
  ]
};
